export type BootstrapTaskLike = {
  task_metadata?: Record<string, unknown> | null;
};

function readAutoGeneratedFlag(value: unknown): boolean {
  return value === true || value === "true";
}

export function isBootstrapTask(task: BootstrapTaskLike | null | undefined): boolean {
  if (!task) return false;
  return readAutoGeneratedFlag(task.task_metadata?.auto_generated);
}

export function getProgressTaskSlice<T extends BootstrapTaskLike>(tasks: T[] | null | undefined): T[] {
  const rows: T[] = Array.isArray(tasks) ? tasks : [];
  const deliveryTasks = rows.filter((task) => !isBootstrapTask(task));
  return deliveryTasks.length > 0 ? deliveryTasks : [];
}

export function hasDeliveryTasks<T extends BootstrapTaskLike>(tasks: T[] | null | undefined): boolean {
  return getProgressTaskSlice(tasks).length > 0;
}
