export type BootstrapTaskLike = {
  sprint_id?: string | null;
  task_metadata?: Record<string, unknown> | null;
};

export type BootstrapSprintLike = {
  id: string;
  auto_generated?: boolean | null;
  phase_key?: string | null;
};

const BOOTSTRAP_PHASE_KEYS = new Set(["discover"]);

function readAutoGeneratedFlag(value: unknown): boolean {
  return value === true || value === "true";
}

function readPhaseKey(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

export function isBootstrapPhaseKey(value: unknown): boolean {
  const phaseKey = readPhaseKey(value);
  return phaseKey ? BOOTSTRAP_PHASE_KEYS.has(phaseKey) : false;
}

export function isBootstrapTask(task: BootstrapTaskLike | null | undefined): boolean {
  if (!task) return false;
  const phaseKey = readPhaseKey(task.task_metadata?.phase_key);
  if (phaseKey) return isBootstrapPhaseKey(phaseKey);
  return readAutoGeneratedFlag(task.task_metadata?.auto_generated);
}

export function getBootstrapSprintIds(sprints: BootstrapSprintLike[] | null | undefined): Set<string> {
  const rows = Array.isArray(sprints) ? sprints : [];
  return new Set(
    rows
      .filter((sprint) => isBootstrapPhaseKey(sprint.phase_key) || (!sprint.phase_key && sprint.auto_generated))
      .map((sprint) => sprint.id)
  );
}

export function matchesBootstrapTruth(task: BootstrapTaskLike | null | undefined, bootstrapSprintIds?: ReadonlySet<string>): boolean {
  if (!task) return false;
  return isBootstrapTask(task) || (task.sprint_id ? bootstrapSprintIds?.has(task.sprint_id) === true : false);
}

export function getProgressTaskSlice<T extends BootstrapTaskLike>(tasks: T[] | null | undefined): T[] {
  const rows: T[] = Array.isArray(tasks) ? tasks : [];
  const deliveryTasks = rows.filter((task) => !isBootstrapTask(task));
  return deliveryTasks.length > 0 ? deliveryTasks : [];
}

export function hasDeliveryTasks<T extends BootstrapTaskLike>(tasks: T[] | null | undefined): boolean {
  return getProgressTaskSlice(tasks).length > 0;
}
