export type BootstrapTaskLike = {
  sprint_id?: string | null;
  task_metadata?: Record<string, unknown> | null;
};

export type BootstrapSprintLike = {
  id: string;
  auto_generated?: boolean | null;
};

function readAutoGeneratedFlag(value: unknown): boolean {
  return value === true || value === "true";
}

export function isBootstrapTask(task: BootstrapTaskLike | null | undefined): boolean {
  if (!task) return false;
  return readAutoGeneratedFlag(task.task_metadata?.auto_generated);
}

export function getBootstrapSprintIds(sprints: BootstrapSprintLike[] | null | undefined): Set<string> {
  const rows = Array.isArray(sprints) ? sprints : [];
  return new Set(rows.filter((sprint) => sprint.auto_generated).map((sprint) => sprint.id));
}

export function matchesBootstrapTruth(task: BootstrapTaskLike | null | undefined, bootstrapSprintIds?: ReadonlySet<string>): boolean {
  if (!task) return false;
  return isBootstrapTask(task) || (task.sprint_id ? bootstrapSprintIds?.has(task.sprint_id) === true : false);
}

export function getProgressTaskSlice<T extends BootstrapTaskLike>(tasks: T[] | null | undefined): T[] {
  const rows: T[] = Array.isArray(tasks) ? tasks : [];
  const deliveryTasks = rows.filter((task) => !isBootstrapTask(task));
  return deliveryTasks.length > 0 ? deliveryTasks : [];
}

export function hasDeliveryTasks<T extends BootstrapTaskLike>(tasks: T[] | null | undefined): boolean {
  return getProgressTaskSlice(tasks).length > 0;
}
