"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import Link from "next/link";
import { RevisionRequestCard } from "@/components/project/revision-request-card";
import { useParams, useSearchParams } from "next/navigation";
import {
  ArrowLeft,
  ArrowUpRight,
  Clock3,
  FolderKanban,
  PauseCircle,
  PlayCircle,
  Plus,
  Sparkles,
  Trash2,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PageHero } from "@/components/ui/page-hero";
import { BrandedEmptyState } from "@/components/ui/branded-empty-state";
import { ProjectTypeBadge } from "@/components/ui/project-badges";
import { formatRelativeTimestamp, getExecutionTone, isStaleExecutionTimestamp, ProgressRing } from "@/components/ui/execution-visibility";
import {
  formatIntakeValue,
} from "@/lib/project-intake";
import { getProjectStatusTone } from "@/lib/project-ui";
import { getProjectLinkEntries, getProjectLinkSuggestions, PROJECT_LINK_FIELDS, PROJECT_LINK_LABELS, type ProjectLinks } from "@/lib/project-links";
import { parseGitHubRepoUrl, type GitHubRepoBinding, type GitHubRepoProvenance } from "@/lib/github-repo-binding";
import { StructuredTaskModal, type StructuredTaskPayload } from "@/components/project/structured-task-modal";
import { TASK_TYPE_CONFIG } from "@/lib/task-model";
import { getBootstrapSprintIds, matchesBootstrapTruth } from "@/lib/project-bootstrap";
import { useRealtimeStore } from "@/lib/realtime-store";
import { cn } from "@/lib/utils";
import { deriveReviewCheckpointState } from "@/lib/review-checkpoint-state";
import { deriveMilestoneDisplayState, deriveMilestoneReviewCardCopy, deriveProjectDetailHeaderState, getCompletedProjectRevisionMilestones, shouldShowAttachmentKickoffBanner } from "@/lib/project-detail-state";

const PROJECT_CREATE_HANDOFF_KEY = "project-create-handoff";

type ProjectDocument = {
  id: string;
  type: string;
  title: string;
  url?: string | null;
  storage_path?: string | null;
  mime_type?: string | null;
  size_bytes?: number | null;
  created_at: string;
};

type ProofItem = {
  id: string;
  kind: string;
  label: string;
  url: string | null;
  storagePath: string | null;
  notes: string | null;
  metadata?: Record<string, unknown> | null;
  sortOrder?: number;
};

function proofItemHref(item: ProofItem) {
  return item.url || null;
}

type MilestoneReviewSummary = {
  checkpointType?: string | null;
  evidenceRequirements?: Record<string, unknown> | null;
  latestSubmissionId: string | null;
  latestSubmissionStatus: string | null;
  latestRevisionNumber: number | null;
  latestSubmissionSummary: string | null;
  latestDecision: string | null;
  latestDecisionNotes: string | null;
  latestRejectionComment?: string | null;
  latestSubmittedAt: string | null;
  proofBundleId: string | null;
  proofBundleTitle: string | null;
  proofCompletenessStatus: string | null;
  proofItemCount: number;
  proofItems?: ProofItem[];
  screenshotItemCount?: number;
  feedbackItemCount: number;
};

type ReviewArtifact = {
  kind: "preview_url" | "workspace_file" | "git_commit";
  label: string;
  value: string;
  sourceTaskId?: string;
  sourceTaskTitle?: string;
};

type PreBuildCheckpointView = {
  applicable: boolean;
  outcome: "match" | "mismatch" | "manual_review" | null;
  status: "approved" | "pending" | "not_requested";
  title: string | null;
  summary: string | null;
  reasons: string[];
};

type Milestone = {
  id: string;
  name: string;
  goal?: string | null;
  status: string;
  phaseKey?: string | null;
  phaseOrder?: number | null;
  autoGenerated?: boolean;
  category?: "bootstrap" | "delivery";
  approvalGateRequired?: boolean;
  approvalGateStatus?: string;
  deliveryReviewRequired?: boolean;
  deliveryReviewStatus?: string | null;
  checkpointType?: string | null;
  checkpointEvidenceRequirements?: Record<string, unknown> | null;
  totalTasks: number;
  doneTasks: number;
  queuedTasks?: number;
  runningTasks?: number;
  blockedTasks?: number;
  hiddenBootstrapTasks?: number;
  progressPct: number;
  reviewArtifacts?: ReviewArtifact[] | null;
  reviewRequest?: {
    id: string;
    jobId?: string | null;
    status: string;
    summary?: string | null;
    createdAt: string;
    links?: ProjectLinks | null;
  } | null;
  reviewSummary?: MilestoneReviewSummary | null;
  preBuildCheckpoint?: PreBuildCheckpointView | null;
};

type ProjectDetail = {
  deliveryIntegrity?: {
    requiresGitHubRepo?: boolean;
    hasGitHubRepo?: boolean;
    pendingProvisioning?: boolean;
    pendingProvisioningReason?: string | null;
    blockingReason?: string | null;
    completionBlocked?: boolean;
    completionCapPct?: number | null;
  };
  project: {
    name: string;
    status: string;
    type?: string | null;
    progress_pct: number;
    intake_summary?: string | null;
    updated_at: string;
    description?: string | null;
    intake?: any;
    links?: ProjectLinks | null;
    github_repo_binding?: GitHubRepoBinding | null;
    github_repo_provenance?: GitHubRepoProvenance | null;
    preBuildCheckpoint?: PreBuildCheckpointView | null;
    [key: string]: any;
  };
  teams: any[];
  milestones: Milestone[];
  tasks: any[];
  events: any[];
  recentSignals?: Array<{
    id: string;
    kind: "blocked" | "approval" | "completed" | "progress" | "activity";
    title: string;
    detail: string;
    timestamp: string;
    actorName?: string | null;
  }>;
  truth?: {
    progressPct: number;
    headline: string;
    summary: string;
    execution: {
      key: string;
      label: string;
      description: string;
    };
    counts: {
      delivery: { total: number; queued: number; running: number; done: number; blocked: number };
      bootstrap: { total: number; queued: number; running: number; done: number; blocked: number };
      all: { total: number };
      jobs: { queued: number; running: number; blocked: number };
    };
    guardrails?: {
      stuckWorkflow?: {
        activeSprintId: string;
        activeSprintName: string;
        nextSprintId: string;
        nextSprintName: string;
        reason: string;
        detail: string;
      } | null;
    };
    taskBoard?: {
      queued: string[];
      inProgress: string[];
      stalled: string[];
      done: string[];
      blockers?: Record<string, { key: string; label: string; detail: string; resolution?: string | null; actionableBy?: string | null; cta?: string | null }>;
    };
  };
  executionVisibility?: {
    queuedReasons?: Array<{
      taskId: string;
      taskTitle: string;
      sprintId?: string | null;
      status: string;
      label: string;
      detail: string;
    }>;
  };
  stats: {
    totalTasks: number;
    doneTasks: number;
    queuedTasks?: number;
    blockedTasks: number;
    inProgressTasks: number;
    bootstrapTasks?: number;
    pendingApprovals?: number;
  };
};

function TaskStatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    todo: "border-zinc-200 bg-zinc-100 text-zinc-600",
    in_progress: "border-blue-200 bg-blue-100 text-blue-700",
    review: "border-purple-200 bg-purple-100 text-purple-700",
    done: "border-emerald-200 bg-emerald-100 text-emerald-700",
    blocked: "border-red-200 bg-red-100 text-red-700",
    cancelled: "border-slate-200 bg-slate-100 text-slate-600",
  };
  return (
    <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em]", styles[status] || styles.todo)}>
      {status.replace("_", " ")}
    </span>
  );
}

function formatReviewStatus(value?: string | null) {
  if (!value || value === "not_requested") return "No review started";
  return value.replace(/_/g, " ");
}

function formatProofItemKind(kind?: string | null) {
  if (!kind) return "Artifact";
  switch (kind) {
    case "staging_url":
      return "Staging URL";
    case "github_pr":
      return "GitHub PR";
    default:
      return kind.replace(/_/g, " ");
  }
}

function checkpointTone(value?: string | null) {
  switch (value) {
    case "approved":
      return "border-emerald-200 bg-emerald-50 text-emerald-700";
    case "pending":
    case "ready_for_review":
      return "border-violet-200 bg-violet-50 text-violet-700";
    case "rejected":
    case "changes_requested":
      return "border-red-200 bg-red-50 text-red-700";
    case "awaiting_evidence":
    case "setup_required":
      return "border-amber-200 bg-amber-50 text-amber-700";
    default:
      return "border-zinc-200 bg-zinc-100 text-zinc-600";
  }
}

function proofTone(value?: string | null) {
  switch (value) {
    case "ready":
      return "border-emerald-200 bg-emerald-50 text-emerald-700";
    case "needs_update":
      return "border-amber-200 bg-amber-50 text-amber-700";
    default:
      return "border-zinc-200 bg-zinc-100 text-zinc-600";
  }
}

function isPrebuildCheckpointMilestone(milestone: Milestone) {
  const checkpointType = milestone.reviewSummary?.checkpointType || milestone.checkpointType;
  return checkpointType === "prebuild_checkpoint";
}

function isBlockerOnlyCheckpoint(milestone: Milestone) {
  return isPrebuildCheckpointMilestone(milestone)
    && milestone.preBuildCheckpoint?.outcome != null
    && milestone.preBuildCheckpoint.outcome !== "match"
    && !milestone.reviewRequest;
}

function checkpointSummaryCopy(input: {
  summary?: MilestoneReviewSummary | null;
  preBuildCheckpoint?: PreBuildCheckpointView | null;
  checkpointState: ReturnType<typeof deriveReviewCheckpointState>;
  fallbackArtifactsCount?: number;
}) {
  if (input.preBuildCheckpoint?.outcome && input.preBuildCheckpoint.outcome !== "match") {
    return input.preBuildCheckpoint.summary || input.summary?.latestSubmissionSummary || "Build is blocked until the repo and stack contract are resolved.";
  }
  if (input.summary?.latestSubmissionSummary) return input.summary.latestSubmissionSummary;
  if (input.preBuildCheckpoint?.summary) return input.preBuildCheckpoint.summary;

  switch (input.checkpointState.key) {
    case "awaiting_submission":
      return input.fallbackArtifactsCount && input.fallbackArtifactsCount > 0
        ? "Work is ready for sign-off, but the formal review packet has not been created yet. Open details to inspect the available artifacts."
        : "No review packet has been submitted yet.";
    case "setup_required":
      return "This checkpoint is blocked on repo setup, so review cannot start yet.";
    case "awaiting_evidence":
      return "A submission exists, but the review evidence is not complete yet.";
    case "changes_requested":
      return "This checkpoint is waiting on updates before it can be approved.";
    case "approved":
      return "This checkpoint is approved and ready to move forward.";
    default:
      return "This checkpoint is ready for review and decision.";
  }
}

function isCheckpointApproved(summary?: MilestoneReviewSummary | null, approvalGateStatus?: string | null) {
  return summary?.latestDecision === "approve" || approvalGateStatus === "approved";
}

function shouldShowCheckpointDecisionMetadata(summary?: MilestoneReviewSummary | null, approvalGateStatus?: string | null) {
  return !isCheckpointApproved(summary, approvalGateStatus);
}

function formatCheckpointReason(reason?: string | null) {
  if (!reason) return null;

  return reason
    .replace(/^Manual review required for unsupported requirement kinds:\s*/i, "Needs manual review because these requirement types could not be auto-checked: ")
    .replace(/^Missing required project artifact:\s*/i, "Missing required project artifact: ")
    .replace(/^Code-heavy delivery cannot advance to review or completion without a real GitHub repo linked to the project\.?/i, "Add a real GitHub repo to this project before this checkpoint can be approved.")
    .replace(/^GitHub repo provisioning is in progress for this code-heavy project\. A real repo will still be required before review or completion\.?/i, "GitHub repo setup is still in progress. This checkpoint stays blocked until a real repo is linked.");
}

function formatTaskStatusLabel(value?: string | null) {
  if (!value) return "Unknown";
  return value.replace(/_/g, " ");
}

function taskProgressValue(task: any) {
  if (!task) return null;

  if (task.status === "done" || task.status === "completed") {
    return 100;
  }

  if (typeof task?.progress_pct === "number" && Number.isFinite(task.progress_pct)) {
    return Math.max(0, Math.min(100, task.progress_pct));
  }

  return null;
}

function isTaskExecutionStale(task: { status?: string | null; updated_at?: string | null } | null | undefined) {
  if (!task || task.status !== "in_progress") return false;
  return isStaleExecutionTimestamp(task.updated_at, 1 * 60 * 1000);
}

function isBootstrapTask(task: any, bootstrapSprintIds?: ReadonlySet<string>) {
  return matchesBootstrapTruth(task, bootstrapSprintIds);
}

function formatBytes(value?: number | null) {
  if (!value) return null;
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${Math.round(value / 1024)} KB`;
  return `${(value / (1024 * 1024)).toFixed(1)} MB`;
}

function artifactEmptyState(projectType?: string | null, intake?: any) {
  if (intake?.shape === "launch-campaign" || ["marketing_growth", "marketing"].includes(projectType || "")) {
    return "No campaign links or creative artifacts added yet.";
  }
  if (["product_build", "ops_enablement", "saas", "web_app", "native_app"].includes(projectType || "")) {
    return "No repo, environment, or build links added yet.";
  }
  return "No project links or artifacts added yet.";
}

function formatUpdatedDate(value?: string | null) {
  if (!value) return "Recently updated";

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Recently updated";

  return `Updated ${date.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  })}`;
}

function EmptySectionState({ icon, title, description, action }: { icon: ReactNode; title: string; description: string; action?: ReactNode }) {
  return <BrandedEmptyState icon={icon} title={title} description={description} action={action} className="border-zinc-200 bg-zinc-50 py-12" />;
}

function Section({ title, description, children, className, action }: { title: string; description?: string; children: ReactNode; className?: string; action?: ReactNode }) {
  return (
    <Card variant="soft" className={cn("overflow-hidden rounded-[24px] border-zinc-200/90", className)}>
      <CardContent className="p-5 sm:p-6">
        <div className="mb-5 flex items-start justify-between gap-3">
          <div>
            <h2 className="text-lg font-semibold tracking-tight text-zinc-950">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-zinc-500">{description}</p> : null}
          </div>
          {action}
        </div>
        {children}
      </CardContent>
    </Card>
  );
}

function MilestoneReviewCard({
  projectId,
  milestone,
  documents,
  onSaved,
}: {
  projectId: string;
  milestone: Milestone;
  documents: ProjectDocument[];
  onSaved: () => void;
}) {
  const { milestoneDisplayState, summaryCopy, helperCopy, showRevisionRequestCard } = deriveMilestoneReviewCardCopy(milestone);
  const revisionCycleActive = milestoneDisplayState.stageState.key === "revision_cycle";
  const deliveryApproved = milestoneDisplayState.stageState.key === "iteration_shipped";

  const stateBadge = milestoneDisplayState.stageState;

  return (
    <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-sm font-semibold text-zinc-900">{milestone.name}</p>
            <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em] text-zinc-600">{milestone.progressPct}% complete</span>
            <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em]", stateBadge.className)}>{stateBadge.label}</span>
            {revisionCycleActive ? <span className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em] text-red-700">Revision requested</span> : null}
          </div>
          {milestone.goal ? <p className="mt-2 text-sm leading-6 text-zinc-600">{milestone.goal}</p> : null}
          <p className="mt-2 text-sm leading-6 text-zinc-600">{summaryCopy}</p>
        </div>
        <TaskStatusBadge status={milestone.status === "active" ? "in_progress" : milestone.status === "completed" ? "done" : milestone.status === "blocked" ? "blocked" : "todo"} />
      </div>

      {showRevisionRequestCard ? (
        <div className="mt-4">
          <RevisionRequestCard
            projectId={projectId}
            sprintId={milestone.id}
            sprintName={milestone.name}
            documents={documents}
            onSubmitted={onSaved}
            hasActiveRevisionCycle={revisionCycleActive}
            shippedApproved={deliveryApproved}
          />
        </div>
      ) : (
        <div className="mt-4 rounded-2xl border border-dashed border-zinc-200 bg-zinc-50 px-4 py-3 text-sm text-zinc-500">
          {helperCopy}
        </div>
      )}
    </div>
  );
}

function CreatedFromIntakeBanner() {
  return (
    <div className="rounded-[24px] border border-emerald-200 bg-emerald-50 px-5 py-4 text-emerald-950 shadow-sm">
      <div className="flex items-start gap-3">
        <div className="mt-0.5 inline-flex h-9 w-9 items-center justify-center rounded-full bg-emerald-600 text-white shadow-sm">
          <Sparkles className="h-4 w-4" />
        </div>
        <div>
          <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-emerald-700">Project handoff complete</div>
          <h2 className="mt-1 text-lg font-semibold text-emerald-950">Project created successfully</h2>
          <p className="mt-1 text-sm leading-6 text-emerald-900/80">You are now in the created project workspace. Intake uploads continue to load here with the rest of the project detail data.</p>
        </div>
      </div>
    </div>
  );
}

export default function ProjectDetailPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const projectId = params.id as string;
  const createdFromIntakeQuery = searchParams.get("created") === "1";
  const agentsById = useRealtimeStore((s) => s.agentsById);
  const projectsById = useRealtimeStore((s) => s.projectsById);
  const approvalsById = useRealtimeStore((s) => s.approvalsById);
  const jobsById = useRealtimeStore((s) => s.jobsById);
  const storeEvents = useRealtimeStore((s) => s.events);

  const [data, setData] = useState<ProjectDetail | null>(null);
  const [documents, setDocuments] = useState<ProjectDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [showTaskModal, setShowTaskModal] = useState(false);
  const [selectedTask, setSelectedTask] = useState<any>(null);
  const [taskModalMode, setTaskModalMode] = useState<"view" | "edit">("view");
  const [creatingTask, setCreatingTask] = useState(false);
  const [taskDesc, setTaskDesc] = useState("");
  const [dismissedUpdateIds, setDismissedUpdateIds] = useState<string[]>([]);
  const [clearedFeedAt, setClearedFeedAt] = useState<string | null>(null);
  const [createdFromIntake, setCreatedFromIntake] = useState(createdFromIntakeQuery);

  const activityStorageKey = useMemo(() => `project-detail-activity:${projectId}`, [projectId]);

  const fetchProject = useCallback(async (showSpinner = false) => {
    if (showSpinner) setLoading(true);
    try {
      const projectRes = await fetch(`/api/projects/${projectId}`, { cache: "no-store" });

      if (!projectRes.ok) {
        const err = await projectRes.json().catch(() => ({ error: "Failed to load project" }));
        throw new Error(err.error || "Failed to load project");
      }

      const json = await projectRes.json();
      setData(json);
      setError(null);
    } catch (e: any) {
      setError(e.message || "Failed to load project");
    } finally {
      if (showSpinner) setLoading(false);
    }
  }, [projectId]);

  const fetchDocuments = useCallback(async () => {
    try {
      const docsRes = await fetch(`/api/projects/${projectId}/documents`, { cache: "no-store" });
      if (!docsRes.ok) {
        setDocuments([]);
        return;
      }
      const docsJson = await docsRes.json();
      setDocuments(docsJson.documents || []);
    } catch {
      setDocuments([]);
    }
  }, [projectId]);

  useEffect(() => {
    if (projectId) {
      fetchProject(true);
      fetchDocuments();
    }
  }, [projectId, fetchProject, fetchDocuments]);

  useEffect(() => {
    if (createdFromIntakeQuery) {
      setCreatedFromIntake(true);
      return;
    }

    if (typeof window === "undefined" || !projectId) return;

    try {
      const raw = window.sessionStorage.getItem(PROJECT_CREATE_HANDOFF_KEY);
      if (!raw) {
        setCreatedFromIntake(false);
        return;
      }

      const handoff = JSON.parse(raw) as { projectId?: string; createdAt?: string };
      const createdAtMs = handoff.createdAt ? new Date(handoff.createdAt).getTime() : 0;
      const isFresh = Number.isFinite(createdAtMs) && Date.now() - createdAtMs < 5 * 60 * 1000;
      const matchesProject = handoff.projectId === projectId;

      if (matchesProject && isFresh) {
        setCreatedFromIntake(true);
        window.sessionStorage.removeItem(PROJECT_CREATE_HANDOFF_KEY);
        return;
      }

      setCreatedFromIntake(false);
    } catch {
      setCreatedFromIntake(false);
    }
  }, [createdFromIntakeQuery, projectId]);

  const attachmentProcessingState = useMemo(() => {
    const state = data?.project?.intake?.attachmentKickoffState;
    return state && typeof state === "object" ? state as {
      status?: string;
      label?: string;
      detail?: string;
      progressPct?: number;
      active?: boolean;
      updatedAt?: string;
      fileCount?: number;
      error?: string;
    } : null;
  }, [data]);

  const attachmentRequirementSources = useMemo(() => {
    const rawSources = data?.project?.intake?.requirements?.sources;
    if (!Array.isArray(rawSources)) return [];
    return rawSources.filter((source: any) => source && source.type !== "intake" && Array.isArray(source.evidence) && source.evidence.length > 0);
  }, [data]);

  useEffect(() => {
    if (!createdFromIntake || !projectId) return;

    const needsDocumentRetry = documents.length === 0;
    const needsRequirementRetry = attachmentRequirementSources.length === 0;
    const isAttachmentActive = Boolean(attachmentProcessingState?.active);
    if (!needsDocumentRetry && !needsRequirementRetry && !isAttachmentActive) return;

    const retryTimers = [1000, 5000, 15000].map((delay) => window.setTimeout(() => {
      if (needsDocumentRetry || isAttachmentActive) void fetchDocuments();
      if (needsRequirementRetry || isAttachmentActive) void fetchProject();
    }, delay));

    let pollTimer: number | null = null;
    if (isAttachmentActive) {
      const pollDelays = [5000, 10000, 15000, 30000];
      let pollAttempt = 0;

      const schedulePoll = () => {
        const delay = pollDelays[Math.min(pollAttempt, pollDelays.length - 1)];
        pollTimer = window.setTimeout(async () => {
          pollAttempt += 1;
          await Promise.all([fetchProject(false), fetchDocuments()]);
          schedulePoll();
        }, delay);
      };

      schedulePoll();
    }

    return () => {
      retryTimers.forEach((timer) => window.clearTimeout(timer));
      if (pollTimer) window.clearTimeout(pollTimer);
    };
  }, [attachmentProcessingState?.active, attachmentRequirementSources.length, createdFromIntake, documents.length, fetchDocuments, fetchProject, projectId]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(activityStorageKey);
      if (!raw) {
        setDismissedUpdateIds([]);
        setClearedFeedAt(null);
        return;
      }
      const parsed = JSON.parse(raw) as { dismissedIds?: string[]; clearedAt?: string | null };
      setDismissedUpdateIds(Array.isArray(parsed.dismissedIds) ? parsed.dismissedIds : []);
      setClearedFeedAt(typeof parsed.clearedAt === "string" ? parsed.clearedAt : null);
    } catch {
      setDismissedUpdateIds([]);
      setClearedFeedAt(null);
    }
  }, [activityStorageKey]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem(activityStorageKey, JSON.stringify({ dismissedIds: dismissedUpdateIds, clearedAt: clearedFeedAt }));
  }, [activityStorageKey, clearedFeedAt, dismissedUpdateIds]);

  const realtimeRefreshState = useMemo(() => {
    const realtimeProject = projectsById.get(projectId);
    const realtimeEvents = storeEvents.filter((event) => event.project_id === projectId);
    const realtimeApprovals = Array.from(approvalsById.values()).filter((approval) => approval.project_id === projectId);
    const realtimeJobs = Array.from(jobsById.values()).filter((job) => job.project_id === projectId);

    const projectUpdatedAt = realtimeProject?.updated_at || "";
    const latestEventTs = realtimeEvents[0]?.timestamp || "";
    const approvalsKey = realtimeApprovals
      .map((approval) => `${approval.id}:${approval.status}:${approval.created_at}`)
      .sort()
      .join("|");
    const jobsKey = realtimeJobs
      .map((job) => `${job.id}:${job.status}`)
      .sort()
      .join("|");

    const freshnessCandidates = [projectUpdatedAt, latestEventTs, ...realtimeApprovals.map((approval) => approval.created_at || "")]
      .filter(Boolean)
      .map((value) => new Date(value).getTime())
      .filter((value) => Number.isFinite(value));
    const freshestRealtimeMs = freshnessCandidates.sort((a, b) => b - a)[0] ?? null;
    const isFresh = Boolean(freshestRealtimeMs && Date.now() - freshestRealtimeMs < 60 * 1000);

    return {
      key: [projectUpdatedAt, latestEventTs, approvalsKey, jobsKey].join("::"),
      isFresh,
    };
  }, [approvalsById, jobsById, projectId, projectsById, storeEvents]);

  useEffect(() => {
    if (!projectId) return;

    let cancelled = false;

    const tick = async () => {
      if (cancelled || document.visibilityState !== "visible" || !navigator.onLine) return;
      if (realtimeRefreshState.isFresh) return;
      await Promise.all([fetchProject(false), fetchDocuments()]);
    };

    const interval = window.setInterval(tick, 60000);
    const onVisible = () => {
      if (document.visibilityState === "visible") void tick();
    };

    document.addEventListener("visibilitychange", onVisible);
    window.addEventListener("online", onVisible);

    return () => {
      cancelled = true;
      window.clearInterval(interval);
      document.removeEventListener("visibilitychange", onVisible);
      window.removeEventListener("online", onVisible);
    };
  }, [projectId, fetchDocuments, fetchProject, realtimeRefreshState.isFresh]);

  useEffect(() => {
    if (!projectId || loading || !data) return;
    if (!realtimeRefreshState.key) return;

    const timeout = window.setTimeout(() => {
      if (document.visibilityState === "visible" && navigator.onLine) {
        void Promise.all([fetchProject(false), fetchDocuments()]);
      }
    }, 500);

    return () => window.clearTimeout(timeout);
  }, [projectId, loading, data, realtimeRefreshState.key, fetchDocuments, fetchProject]);

  const handleStatusChange = async (newStatus: string) => {
    setActionLoading(newStatus);
    setError(null);
    setData((prev) => (prev ? { ...prev, project: { ...prev.project, status: newStatus, updated_at: new Date().toISOString() } } : prev));

    try {
      const res = await fetch(`/api/projects/${projectId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus }),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || "Failed to update");
      setData((prev) => (prev ? { ...prev, project: { ...prev.project, ...json.project } } : prev));
    } catch (e: any) {
      setError(e.message || "Failed to update");
      await fetchProject(false);
    } finally {
      setActionLoading(null);
    }
  };

  const handleDelete = async () => {
    setActionLoading("delete");
    try {
      const res = await fetch(`/api/projects/${projectId}`, { method: "DELETE" });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || "Failed to delete");
      window.location.href = "/projects";
    } catch (e: any) {
      setError(e.message);
    } finally {
      setActionLoading(null);
      setShowDeleteConfirm(false);
    }
  };

  const handleCreateTask = async (payload: StructuredTaskPayload) => {
    setCreatingTask(true);
    try {
      const res = await fetch(`/api/projects/${projectId}/tasks`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || "Failed to create task");
      setSelectedTask(null);
      setShowTaskModal(false);
      setTaskModalMode("view");
      await fetchProject(false);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setCreatingTask(false);
    }
  };

  const handleUpdateTask = async () => {
    if (!selectedTask) return;
    try {
      const res = await fetch(`/api/projects/${projectId}/tasks/${selectedTask.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ notes: taskDesc, status: selectedTask.status }),
      });
      if (!res.ok) throw new Error("Failed to save task");
      setShowTaskModal(false);
      setTaskModalMode("view");
      await fetchProject(false);
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleDeleteTask = async () => {
    if (!selectedTask) return;
    try {
      const res = await fetch(`/api/projects/${projectId}/tasks/${selectedTask.id}`, {
        method: "DELETE",
      });
      if (!res.ok) throw new Error("Failed to delete task");
      setSelectedTask(null);
      setShowTaskModal(false);
      setTaskModalMode("view");
      await fetchProject(false);
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleTaskClick = (task: any) => {
    setSelectedTask(task);
    setTaskDesc(task.description || "");
    setTaskModalMode("view");
    setShowTaskModal(true);
  };

  const project = data?.project ?? null;
  const milestones = useMemo(() => data?.milestones ?? [], [data?.milestones]);
  const tasks = useMemo(() => data?.tasks ?? [], [data?.tasks]);
  const deliveryIntegrity = data?.deliveryIntegrity;
  const truth = data?.truth;
  const executionVisibility = data?.executionVisibility;

  const taskGroups = useMemo(() => {
    const truthBoard = truth?.taskBoard;
    if (!truthBoard) {
      return {
        todo: tasks.filter((task: any) => task.status === "todo"),
        inProgress: tasks.filter((task: any) => task.status === "in_progress" || task.status === "review"),
        done: tasks.filter((task: any) => task.status === "done"),
        blocked: tasks.filter((task: any) => task.status === "blocked"),
      };
    }

    const byId = new Map(tasks.map((task: any) => [task.id, task]));
    return {
      todo: truthBoard.queued.map((id) => byId.get(id)).filter(Boolean),
      inProgress: truthBoard.inProgress.map((id) => byId.get(id)).filter(Boolean),
      done: truthBoard.done.map((id) => byId.get(id)).filter(Boolean),
      blocked: truthBoard.stalled.map((id) => byId.get(id)).filter(Boolean),
    };
  }, [tasks, truth?.taskBoard]);

  useEffect(() => {
    if (!showTaskModal) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return;
      setSelectedTask(null);
      setShowTaskModal(false);
      setTaskModalMode("view");
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [showTaskModal]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 p-12">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-red-200 border-t-red-600" />
        <div className="text-zinc-500">Loading project…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6">
        <Card className="rounded-[24px] border-red-200 bg-red-50 shadow-sm">
          <CardContent className="py-6">
            <div className="flex items-center gap-2 font-medium text-red-700">
              <span className="text-xl">⚠️</span>
              <p>Error loading project</p>
            </div>
            <p className="mt-2 text-sm text-red-600">{error}</p>
            <div className="mt-4 flex gap-3">
              <Button onClick={() => fetchProject(true)} variant="destructive" className="rounded-xl">Retry</Button>
              <Link href="/projects" className="inline-flex items-center rounded-xl border border-zinc-300 px-4 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50">
                ← Back to Projects
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!project) {
    return null;
  }

  const bootstrapSprintIds = getBootstrapSprintIds(milestones.map((milestone) => ({ id: milestone.id, auto_generated: milestone.autoGenerated, phase_key: milestone.phaseKey })));
  const intake = project.intake || null;
  const summaryText = project.intake_summary || project.description || intake?.summary || null;
  const actionTargetStatus = project.status === "active" ? "paused" : project.status === "paused" ? "active" : null;
  const actionLabel = actionTargetStatus === "paused" ? "Pause" : actionTargetStatus === "active" ? "Resume" : null;
  const isStatusActionLoading = actionTargetStatus ? actionLoading === actionTargetStatus : false;
  const statusTone = getProjectStatusTone(project.status);
  const headerState = deriveProjectDetailHeaderState({
    projectProgressPct: project.progress_pct,
    truth,
    attachmentKickoffState: attachmentProcessingState,
  });
  const selectedTaskTypeConfig = selectedTask?.task_type ? TASK_TYPE_CONFIG[selectedTask.task_type as keyof typeof TASK_TYPE_CONFIG] : null;
  const reviewableMilestones = milestones
    .filter((milestone) => {
      if (isPrebuildCheckpointMilestone(milestone)) return false;
      if (isBlockerOnlyCheckpoint(milestone)) return false;

      const hasSubmission = Boolean(milestone.reviewSummary?.latestSubmissionId);
      const hasMaterials = (milestone.reviewSummary?.proofItemCount || 0) > 0 || (milestone.reviewArtifacts?.length || 0) > 0;
      const isActionablePhase = milestone.status === "active" || milestone.status === "completed";

      return (milestone.deliveryReviewRequired || milestone.approvalGateRequired || hasSubmission)
        && (isActionablePhase || hasSubmission || hasMaterials);
    })
    .sort((a, b) => {
      const aHasSubmission = Boolean(a.reviewSummary?.latestSubmissionId);
      const bHasSubmission = Boolean(b.reviewSummary?.latestSubmissionId);
      if (aHasSubmission !== bHasSubmission) return aHasSubmission ? -1 : 1;

      const aHasMaterials = (a.reviewSummary?.proofItemCount || 0) > 0 || (a.reviewArtifacts?.length || 0) > 0;
      const bHasMaterials = (b.reviewSummary?.proofItemCount || 0) > 0 || (b.reviewArtifacts?.length || 0) > 0;
      if (aHasMaterials !== bHasMaterials) return aHasMaterials ? -1 : 1;

      const aCompleted = a.totalTasks > 0 && a.doneTasks >= a.totalTasks;
      const bCompleted = b.totalTasks > 0 && b.doneTasks >= b.totalTasks;
      if (aCompleted !== bCompleted) return aCompleted ? -1 : 1;

      const aInReview = (a.deliveryReviewStatus === "pending" || a.approvalGateStatus === "pending");
      const bInReview = (b.deliveryReviewStatus === "pending" || b.approvalGateStatus === "pending");
      if (aInReview !== bInReview) return aInReview ? -1 : 1;

      return (a.phaseOrder ?? Number.MAX_SAFE_INTEGER) - (b.phaseOrder ?? Number.MAX_SAFE_INTEGER);
    });

  const blockerOnlyMilestones = milestones.filter(isBlockerOnlyCheckpoint);
  const completedProjectRevisionMilestones = getCompletedProjectRevisionMilestones(milestones);
  const activeReviewMilestones = reviewableMilestones.filter((milestone) => {
    const stageKey = deriveMilestoneDisplayState(milestone).stageState.key;
    return stageKey !== "iteration_shipped";
  });
  const projectWorkSignalCount = blockerOnlyMilestones.length + activeReviewMilestones.length;

  const executionSummary = truth?.execution ?? { key: "idle", label: statusTone.label, description: "No project work is visible yet." };
  const openTaskCount = Math.max(0, (data?.stats.totalTasks ?? 0) - (data?.stats.doneTasks ?? 0));
  const pendingApprovalCount = data?.stats.pendingApprovals ?? 0;
  const reviewTaskCount = tasks.filter((task: any) => task.review_status && task.review_status !== "not_requested" && task.review_status !== "approved").length;
  const reviewCount = Math.max(reviewTaskCount, activeReviewMilestones.length);
  const blockedWorkCount = Math.max(data?.stats.blockedTasks ?? 0, blockerOnlyMilestones.length);
  const summaryMetrics = [
    { label: "Open tasks", value: openTaskCount },
    { label: "Pending approvals", value: pendingApprovalCount },
    { label: "In review", value: reviewCount },
    { label: "Blocked work", value: blockedWorkCount },
  ];
  const statusBadgeLabel = formatTaskStatusLabel(project.status);
  const statusBadgeTone = project.status === "completed"
    ? "border-emerald-200 bg-emerald-50 text-emerald-700"
    : project.status === "paused"
      ? "border-amber-200 bg-amber-50 text-amber-700"
      : project.status === "active"
        ? "border-blue-200 bg-blue-50 text-blue-700"
        : "border-zinc-200 bg-zinc-100 text-zinc-700";
  const attentionState = blockedWorkCount > 0
    ? {
        label: "Needs unblock",
        tone: "border-red-200 bg-red-50 text-red-700",
        summary: blockedWorkCount === 1 ? "1 work item is blocked and needs attention now." : `${blockedWorkCount} work items are blocked and need attention now.`,
      }
    : pendingApprovalCount > 0
      ? {
          label: "Awaiting approval",
          tone: "border-amber-200 bg-amber-50 text-amber-700",
          summary: pendingApprovalCount === 1 ? "1 approval decision is holding work open." : `${pendingApprovalCount} approval decisions are holding work open.`,
        }
      : reviewCount > 0
        ? {
            label: "Review follow-through",
            tone: "border-violet-200 bg-violet-50 text-violet-700",
            summary: reviewCount === 1 ? "1 item is in or ready for review." : `${reviewCount} items are in or ready for review.`,
          }
        : openTaskCount > 0
          ? {
              label: "Active work",
              tone: "border-blue-200 bg-blue-50 text-blue-700",
              summary: openTaskCount === 1 ? "1 task is still open." : `${openTaskCount} tasks are still open.`,
            }
          : project.status === "completed"
            ? {
                label: "Completed",
                tone: "border-emerald-200 bg-emerald-50 text-emerald-700",
                summary: "All tracked work is complete.",
              }
            : {
                label: "Ready for next step",
                tone: "border-zinc-200 bg-zinc-100 text-zinc-700",
                summary: "No open work is tracked yet.",
              };
  const heroSummary = summaryText || attentionState.summary;
  const operationalDetails = [
    { label: "Review signals", value: String(projectWorkSignalCount) },
    { label: "Queued work", value: String(Math.max(truth?.counts.jobs.queued ?? 0, truth?.counts.delivery.queued ?? 0)) },
    { label: "Running work", value: String(Math.max(truth?.counts.jobs.running ?? 0, truth?.counts.delivery.running ?? 0)) },
  ];
  const recentSignalItems = [
    ...(data?.recentSignals || []).map((signal) => ({
      id: signal.id,
      label: signal.kind === "approval" ? "Approval" : signal.kind === "blocked" ? "Blocked" : signal.kind === "completed" ? "Completed" : signal.kind === "progress" ? "Progress" : "Activity",
      title: signal.title,
      detail: signal.detail,
      timestamp: signal.timestamp,
    })),
    ...blockerOnlyMilestones.map((milestone) => ({
      id: `${milestone.id}-blocked`,
      label: "Blocked",
      title: milestone.name,
      detail: formatCheckpointReason(milestone.preBuildCheckpoint?.reasons?.[0]) || "Resolve the repo and stack checkpoint before Build can start.",
      timestamp: project.updated_at,
    })),
    ...activeReviewMilestones.map((milestone) => ({
      id: `${milestone.id}-review`,
      label: "Review",
      title: milestone.name,
      detail: `${deriveMilestoneDisplayState(milestone).stageState.label} requires follow-through.`,
      timestamp: project.updated_at,
    })),
  ];
  const updatedLabel = formatUpdatedDate(project.updated_at).replace(/^Updated\s+/i, "");
  const queuedPhaseHoldReasons = executionVisibility?.queuedReasons?.filter((reason) => reason.status === "waiting_for_kickoff_completion") || [];
  const exceptionalQueuedHoldReasons = executionVisibility?.queuedReasons?.filter((reason) => reason.status !== "waiting_for_kickoff_completion") || [];
  const queuedPhaseHoldSummary = queuedPhaseHoldReasons.length
    ? `${queuedPhaseHoldReasons.map((reason) => reason.taskTitle).join(" and ")} unlock after earlier phase work finishes.`
    : null;
  const stuckWorkflowGuardrail = truth?.guardrails?.stuckWorkflow ?? null;
  const showAttachmentProcessingBanner = shouldShowAttachmentKickoffBanner(attachmentProcessingState) && headerState.key === "attachment_processing";
  const visibleAttachmentProcessingState = showAttachmentProcessingBanner ? attachmentProcessingState : null;
  const attachmentProcessingTone = attachmentProcessingState?.status === "failed"
    ? "border-red-200 bg-red-50 text-red-900"
    : attachmentProcessingState?.status === "retryable_failure"
      ? "border-amber-200 bg-amber-50 text-amber-900"
      : attachmentProcessingState?.active
        ? "border-sky-200 bg-sky-50 text-sky-900"
        : "border-emerald-200 bg-emerald-50 text-emerald-900";

  return (
    <div className="min-w-0 space-y-6 overflow-x-hidden pb-10 md:space-y-8">
      {showDeleteConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="w-full max-w-md rounded-[24px] bg-white p-6 shadow-xl">
            <h3 className="text-lg font-semibold text-zinc-900">Delete this project?</h3>
            <p className="mt-2 text-sm text-zinc-600">This cannot be undone.</p>
            <div className="mt-4 flex gap-3">
              <Button onClick={() => setShowDeleteConfirm(false)} variant="outline" className="flex-1 rounded-xl">Cancel</Button>
              <Button onClick={handleDelete} disabled={actionLoading === "delete"} variant="destructive" className="flex-1 rounded-xl">
                {actionLoading === "delete" ? "Deleting..." : "Delete"}
              </Button>
            </div>
          </div>
        </div>
      )}

      <PageHero>
        <div className="flex flex-col gap-6 p-5 sm:p-6 lg:flex-row lg:items-end lg:justify-between lg:p-8">
          <div className="max-w-3xl space-y-4">
            <div className="flex flex-wrap items-center gap-2">
              <Link href="/projects" className="inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-white px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-700 transition hover:border-red-200 hover:text-red-700">
                <ArrowLeft className="h-3.5 w-3.5" />
                Back to projects
              </Link>
              <div className="inline-flex items-center gap-2 rounded-full border border-red-200 bg-white px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-red-700">
                <Sparkles className="h-3.5 w-3.5 text-red-500" />
                Project detail
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-2">
                {project.type ? <ProjectTypeBadge type={project.type} status={project.status} className="normal-case tracking-normal" /> : null}
              </div>
              <div>
                <h1 className="break-words text-3xl font-semibold tracking-tight text-zinc-950 sm:text-4xl">{project.name}</h1>
                <p className="mt-2 hidden max-w-2xl text-sm leading-6 text-zinc-600 sm:block sm:text-base">
                  {heroSummary || "Track project context, active tasks, approvals, review, and signals from one page."}
                </p>
              </div>
            </div>

            <div className={cn("rounded-2xl border p-4 sm:p-5", statusTone.surface)}>
              <div className="flex flex-col gap-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="space-y-3">
                    <div className="flex flex-wrap items-center gap-2 text-sm">
                      <span className={cn("rounded-full border px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.14em]", statusBadgeTone)}>
                        Status · {statusBadgeLabel}
                      </span>
                      <span className={cn("rounded-full border px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.14em]", attentionState.tone)}>
                        Attention · {attentionState.label}
                      </span>
                    </div>
                    <div>
                      <p className="text-base font-medium text-zinc-950">{attentionState.summary}</p>
                      <p className="mt-1 text-sm leading-6 text-zinc-600">{executionSummary.description}</p>
                    </div>
                  </div>
                  <div className="rounded-2xl border border-white/80 bg-white/80 px-4 py-3 text-sm text-zinc-600 shadow-sm">
                    <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500">Updated</div>
                    <div className="mt-1 font-medium text-zinc-950">{updatedLabel}</div>
                  </div>
                </div>

                <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                  {summaryMetrics.map((item) => (
                    <div key={item.label} className="rounded-2xl border border-white/80 bg-white/80 px-4 py-3 shadow-sm">
                      <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500">{item.label}</div>
                      <div className="mt-1 text-2xl font-semibold tracking-tight text-zinc-950">{item.value}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="flex w-full flex-col gap-3 lg:w-auto lg:min-w-[320px] lg:max-w-sm">
            <div className="rounded-2xl border border-zinc-200 bg-white p-4">
              <div className="flex items-center gap-2 text-sm font-medium text-zinc-900">
                <Clock3 className="h-4 w-4 text-red-500" />
                Project summary
              </div>
              <p className="mt-1 text-sm leading-6 text-zinc-500">Primary actions and current project state live here; deeper operational details move lower on the page.</p>

              <div className="mt-4 border-t border-zinc-200 pt-4">
                <div className="text-sm font-medium text-zinc-900">Project actions</div>
                <p className="mt-1 text-sm leading-6 text-zinc-500">Add tasks, adjust delivery state, or remove the project without leaving this workspace.</p>
                <div className="mt-4 grid gap-2">
                  {actionTargetStatus && actionLabel ? (
                    <Button
                      onClick={() => handleStatusChange(actionTargetStatus)}
                      disabled={isStatusActionLoading}
                      variant={actionTargetStatus === "paused" ? "outline" : "secondary"}
                      className="w-full justify-center rounded-xl"
                    >
                      {actionTargetStatus === "paused" ? <PauseCircle className="h-4 w-4" /> : <PlayCircle className="h-4 w-4" />}
                      {isStatusActionLoading ? "Updating..." : actionLabel}
                    </Button>
                  ) : null}
                  <Button onClick={() => { setSelectedTask(null); setShowTaskModal(true); }} size="lg" variant="warm" className="w-full rounded-xl">
                    <Plus className="h-4 w-4" />
                    Add follow-up work
                  </Button>
                  <Button onClick={() => setShowDeleteConfirm(true)} variant="outline" className="w-full justify-center rounded-xl border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800">
                    <Trash2 className="h-4 w-4" />
                    Delete project
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </PageHero>

      {createdFromIntake ? <CreatedFromIntakeBanner /> : null}

      <div className="space-y-4">
        <Section title="Project work" description="Tasks are the canonical work surface for scoped delivery, active execution, and follow-up work.">
          {tasks.length === 0 ? (
            <EmptySectionState
              icon={<FolderKanban className="h-7 w-7" />}
              title="No project work yet"
              description="Add the first task to move this project from setup into active delivery. Work items will update here as they move across lanes."
              action={<Button onClick={() => { setSelectedTask(null); setShowTaskModal(true); }} variant="warm" className="rounded-xl px-4">Add first task</Button>}
            />
          ) : (
            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
              {[
                ["Queued work", taskGroups.todo, "border-zinc-200 bg-zinc-50", "queued"],
                ["Active work", taskGroups.inProgress, "border-blue-100 bg-blue-50/60", "in_flight"],
                ["Blocked work", taskGroups.blocked, "border-amber-100 bg-amber-50/70", "stalled"],
                ["Completed work", taskGroups.done, "border-emerald-100 bg-emerald-50/70", "done"],
              ].map(([label, bucket, bucketClass, bucketKey]) => (
                <div key={String(label)} className={cn("rounded-2xl border p-3", String(bucketClass))}>
                  <div className="mb-3 flex items-center justify-between gap-2">
                    <h3 className="text-sm font-semibold text-zinc-900">{label}</h3>
                    <span className="rounded-full border border-zinc-200 bg-white px-2.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.12em] text-zinc-500">{(bucket as any[]).length}</span>
                  </div>
                  <div className="space-y-2">
                    {(bucket as any[]).length === 0 ? (
                      <div className="rounded-xl border border-dashed border-zinc-200 bg-white px-3 py-4 text-xs text-zinc-400">No work items</div>
                    ) : (
                      (bucket as any[]).map((task: any) => {
                        const assignee = task.assignee_agent_id ? agentsById.get(task.assignee_agent_id) : null;
                        const taskTypeConfig = task.task_type ? TASK_TYPE_CONFIG[task.task_type as keyof typeof TASK_TYPE_CONFIG] : null;
                        const taskProgress = taskProgressValue(task);
                        const taskMilestone = task.sprint_id ? milestones.find((milestone) => milestone.id === task.sprint_id) : null;
                        const checkpointState = taskMilestone?.approvalGateRequired || taskMilestone?.deliveryReviewRequired || taskMilestone?.reviewSummary?.latestSubmissionId ? taskMilestone : null;
                        const checkpointDisplayState = checkpointState ? deriveMilestoneDisplayState(checkpointState) : null;
                        const checkpointReviewActive = Boolean(
                          task.review_required
                          && task.status === "todo"
                          && checkpointDisplayState
                          && (checkpointDisplayState.stageState.key === "delivery_review_active" || checkpointDisplayState.stageState.key === "rereview_active")
                        );
                        const effectiveTaskStatus = checkpointReviewActive ? "review" : task.status;
                        const effectiveReviewStatus = checkpointReviewActive ? "in_review" : task.review_status;
                        const executionTone = getExecutionTone({
                          status: effectiveTaskStatus,
                          reviewRequired: task.review_required,
                          reviewStatus: effectiveReviewStatus,
                          stale: isTaskExecutionStale(task),
                        });
                        const showTaskReviewBadge = Boolean(
                          task.review_required
                          && task.status !== "in_progress"
                          && task.status !== "review"
                          && task.status !== "done"
                          && task.review_status
                          && task.review_status !== "not_requested"
                          && task.review_status !== "approved"
                        );
                        const showCheckpointBadge = Boolean(
                          checkpointDisplayState
                          && !isBootstrapTask(task, bootstrapSprintIds)
                          && ["delivery_review_active", "rereview_active", "qa_ready", "qa_queued", "revision_cycle", "iteration_shipped"].includes(checkpointDisplayState.stageState.key)
                        );
                        return (
                          <button key={task.id} onClick={() => handleTaskClick(task)} className="block w-full rounded-xl border border-zinc-200 bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-red-200">
                            <div className="flex items-start justify-between gap-3">
                              <div className="min-w-0 flex-1">
                                <div className="flex items-start justify-between gap-2">
                                  <span className="line-clamp-2 text-sm font-medium text-zinc-900">{task.title}</span>
                                  <TaskStatusBadge status={effectiveTaskStatus} />
                                </div>
                                <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] font-medium uppercase tracking-[0.12em]">
                                  <span className="text-zinc-500">Task</span>
                                  {taskTypeConfig ? <span className="text-red-600">{taskTypeConfig.label}</span> : null}
                                  {taskMilestone?.name ? <span className="text-zinc-400">Stage: {taskMilestone.name}</span> : null}
                                </div>
                                <div className="mt-2 flex flex-wrap gap-2">
                                  <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em]", executionTone.badgeClassName)}>{executionTone.label}</span>
                                  {isBootstrapTask(task, bootstrapSprintIds) ? <span className="rounded-full border border-sky-200 bg-sky-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-sky-700">Kickoff</span> : bucketKey === "done" ? <span className="rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-emerald-700">Completed</span> : bucketKey === "stalled" ? <span className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-amber-700">On hold</span> : bucketKey === "queued" ? <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-zinc-700">Queued next</span> : <span className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-red-700">Active work</span>}
                                  {showTaskReviewBadge ? <span className="rounded-full border border-purple-100 bg-purple-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-purple-700">{formatReviewStatus(task.review_status)}</span> : null}
                                  {showCheckpointBadge ? <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em]", checkpointDisplayState?.stageState.className || checkpointTone(checkpointDisplayState?.checkpointState.key))}>Review gate: {checkpointDisplayState?.stageState.label || checkpointDisplayState?.checkpointState.label}</span> : null}
                                </div>
                                {bucketKey === "stalled" && truth?.taskBoard?.blockers?.[task.id] ? (
                                  <div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 px-3 py-3 text-xs leading-5 text-amber-900">
                                    <div className="font-semibold text-amber-800">{truth.taskBoard.blockers[task.id].label}</div>
                                    <div className="mt-1">{truth.taskBoard.blockers[task.id].detail}</div>
                                    {truth.taskBoard.blockers[task.id].resolution ? <div className="mt-2 text-amber-700">Next: {truth.taskBoard.blockers[task.id].resolution}</div> : null}
                                  </div>
                                ) : null}
                              </div>
                              <ProgressRing value={taskProgress} size={48} strokeWidth={4} />
                            </div>
                            {(task.description || assignee || task.updated_at) && (
                              <div className="mt-2 space-y-1">
                                {task.description && <p className="line-clamp-2 text-xs leading-5 text-zinc-500">{task.description}</p>}
                                <div className="flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-zinc-400">
                                  {assignee ? <p>Owner: {assignee.name}</p> : null}
                                  {task.updated_at ? <p>{formatRelativeTimestamp(task.updated_at)}</p> : null}
                                </div>
                              </div>
                            )}
                          </button>
                        );
                      })
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </Section>

        <Section title="Approvals & review" description="Human decisions stay separate from the main work board, even while later slices refine the exact review model.">
          <div className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold text-zinc-900">Pending approvals</h3>
              <p className="mt-1 text-sm leading-6 text-zinc-500">Approval-specific UI remains limited in this slice, so this section currently surfaces the project approval count and defers deeper approval modeling to later work.</p>
              <div className="mt-3 rounded-2xl border border-zinc-200 bg-white px-4 py-3">
                <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500">Pending approvals</div>
                <div className="mt-1 text-2xl font-semibold tracking-tight text-zinc-950">{data?.stats.pendingApprovals ?? 0}</div>
              </div>
            </div>

            <div className="border-t border-zinc-200 pt-4">
              <h3 className="text-sm font-semibold text-zinc-900">Review & revisions</h3>
              <p className="mt-1 text-sm leading-6 text-zinc-500">Existing review and revision surfaces are preserved, but moved into the dedicated decision section.</p>
              <div className="mt-3 space-y-3">
                {reviewableMilestones.length > 0 ? reviewableMilestones.map((milestone) => (
                  <MilestoneReviewCard
                    key={milestone.id}
                    projectId={projectId}
                    milestone={milestone}
                    documents={documents}
                    onSaved={() => {
                      void Promise.all([fetchProject(false), fetchDocuments()]);
                    }}
                  />
                )) : (
                  <div className="rounded-2xl border border-dashed border-zinc-200 bg-zinc-50 px-4 py-4 text-sm text-zinc-500">No active review items yet.</div>
                )}

                {completedProjectRevisionMilestones.length > 0 ? (
                  <div className="border-t border-zinc-200 pt-4">
                    <h4 className="text-sm font-semibold text-zinc-900">Post-completion revisions</h4>
                    <p className="mt-1 text-sm leading-6 text-zinc-500">Temporary carry-forward surface left intact while later slices finish the review model.</p>
                    <div className="mt-3 space-y-3">
                      {completedProjectRevisionMilestones.map((milestone) => {
                        const milestoneDisplayState = deriveMilestoneDisplayState(milestone);
                        const revisionCycleActive = milestoneDisplayState.stageState.key === "revision_cycle";
                        const deliveryApproved = milestoneDisplayState.stageState.key === "iteration_shipped";
                        return (
                          <RevisionRequestCard
                            key={`${milestone.id}-completed-revision`}
                            projectId={projectId}
                            sprintId={milestone.id}
                            sprintName={milestone.name}
                            documents={documents}
                            onSubmitted={() => {
                              void Promise.all([fetchProject(false), fetchDocuments()]);
                            }}
                            hasActiveRevisionCycle={revisionCycleActive}
                            shippedApproved={deliveryApproved}
                          />
                        );
                      })}
                    </div>
                  </div>
                ) : null}
              </div>
            </div>
          </div>
        </Section>

        <Section title="Recent signals" description="Curated updates and blockers, using the current signal-like sources until the later signal pass lands.">
          {recentSignalItems.length > 0 ? (
            <div className="space-y-3">
              {recentSignalItems.slice(0, 8).map((signal) => (
                <div key={signal.id} className="rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-700">{signal.label}</span>
                    <span className="text-sm font-medium text-zinc-900">{signal.title}</span>
                    <span className="ml-auto text-xs text-zinc-400">{formatRelativeTimestamp(signal.timestamp)}</span>
                  </div>
                  <p className="mt-2 text-sm leading-6 text-zinc-600">{signal.detail}</p>
                </div>
              ))}
            </div>
          ) : (
            <EmptySectionState icon={<Sparkles className="h-7 w-7" />} title="No recent signals" description="Meaningful project updates will appear here once work, approvals, or review activity starts moving." />
          )}
        </Section>

        <Section title="Context" description="Links, documents, uploads, and extracted materials that support the work.">
          <div className="grid gap-4 xl:grid-cols-2">
            <div className="space-y-4">
              <div>
                <h3 className="text-sm font-semibold text-zinc-900">Links</h3>
                <p className="mt-1 text-sm leading-6 text-zinc-500">Relevant repos, previews, docs, and launch assets in one place.</p>
              </div>
              {project.links && Object.keys(project.links).length > 0 ? (
                <div className="space-y-2">
                  {getProjectLinkEntries(project.links).map((link) => (
                    <a key={link.key} href={link.url} target="_blank" rel="noreferrer" className="flex min-w-0 items-start justify-between gap-3 rounded-2xl border border-zinc-200 bg-white px-4 py-3 transition hover:border-red-200">
                      <div className="min-w-0">
                        <div className="text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-400">{link.label}</div>
                        <div className="mt-1 break-all text-sm font-medium text-zinc-900">{link.url}</div>
                      </div>
                      <div className="flex shrink-0 items-center gap-1 text-xs font-medium text-red-600">
                        Open
                        <ArrowUpRight className="h-3.5 w-3.5" />
                      </div>
                    </a>
                  ))}
                </div>
              ) : (
                <EmptySectionState icon={<ArrowUpRight className="h-7 w-7" />} title="No links yet" description={artifactEmptyState(project.type, intake)} />
              )}
            </div>

            <div className="space-y-4">
              <div>
                <h3 className="text-sm font-semibold text-zinc-900">Documents & uploads</h3>
                <p className="mt-1 text-sm leading-6 text-zinc-500">Uploaded references, files, and extracted notes tied to this project.</p>
              </div>
              {(documents.length > 0 || attachmentRequirementSources.length > 0 || createdFromIntake) ? (
                <div className="space-y-3">
                  {attachmentRequirementSources.length > 0 ? (
                    <div className="rounded-[24px] border border-emerald-200 bg-emerald-50/80 p-4">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="rounded-full border border-emerald-200 bg-white px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.14em] text-emerald-700">PDF extraction notes</span>
                        <span className="text-xs text-emerald-800/80">{attachmentRequirementSources.length} source{attachmentRequirementSources.length === 1 ? "" : "s"} parsed into intake requirements</span>
                      </div>
                      <div className="mt-3 space-y-3">
                        {attachmentRequirementSources.map((source: any) => (
                          <div key={`${source.title}-${source.type}`} className="rounded-2xl border border-emerald-200/80 bg-white px-4 py-3 shadow-sm">
                            <div className="flex flex-wrap items-center gap-2">
                              <span className="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-medium uppercase text-emerald-700">{String(source.type || "document").replace(/_/g, " ")}</span>
                              <p className="text-sm font-medium text-zinc-900">{source.title}</p>
                            </div>
                            <ul className="mt-2 space-y-1 text-sm leading-6 text-zinc-700">
                              {(source.evidence || []).slice(0, 4).map((item: string) => (
                                <li key={item} className="flex gap-2">
                                  <span className="mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500" />
                                  <span>{item}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : createdFromIntake ? (
                    <div className="rounded-[24px] border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Attached files are being processed into project requirements now. This page will keep refreshing while extraction and kickoff are running.</div>
                  ) : null}

                  {documents.map((doc) => (
                    <div key={doc.id} className="rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm">
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="rounded-full border border-zinc-200 bg-zinc-100 px-2 py-0.5 text-[10px] font-medium uppercase text-zinc-700">{doc.type.replace(/_/g, " ")}</span>
                            <p className="truncate text-sm font-medium text-zinc-900">{doc.title}</p>
                          </div>
                          <p className="mt-1 text-xs text-zinc-500">{doc.mime_type ? `${doc.mime_type} • ` : ""}Added {new Date(doc.created_at).toLocaleDateString()}</p>
                          {doc.storage_path ? <p className="mt-1 break-all text-[11px] text-zinc-400">{doc.storage_path}</p> : null}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <EmptySectionState icon={<FolderKanban className="h-7 w-7" />} title="No documents or uploads yet" description="Project files, uploaded references, and extracted notes will appear here." />
              )}
            </div>
          </div>
        </Section>

        <Section title="Project details" description="Secondary metadata and operational details live here instead of competing with the core work and decision flow.">
          <div className="grid gap-4 xl:grid-cols-2">
            <div className="space-y-4">
              <div>
                <h3 className="text-sm font-semibold text-zinc-900">Team & ownership</h3>
                <p className="mt-1 text-sm leading-6 text-zinc-500">Who is attached to the work and how the load is shaping up.</p>
              </div>
              {Array.isArray(data?.teams) && data.teams.length > 0 ? (
                <div className="space-y-2">
                  {data.teams.map((team: any) => (
                    <div key={team.id} className="rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm">
                      <div className="flex items-center justify-between gap-2">
                        <p className="text-sm font-medium text-zinc-900">{team.name}</p>
                        <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-700">{team.status === "on_track" ? "On track" : team.status === "waiting" ? "Waiting" : formatIntakeValue(team.status)}</span>
                      </div>
                      <div className="mt-3 grid grid-cols-2 gap-2 text-xs text-zinc-500">
                        <span>{team.memberCount} members</span>
                        <span>{team.activeAgents} active now</span>
                        <span>{team.taskCount} owned tasks</span>
                        <span>{team.completedTasks || 0} completed</span>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="rounded-2xl border border-dashed border-zinc-200 bg-zinc-50 px-4 py-4 text-sm text-zinc-500">No team assignments are attached to this project yet.</div>
              )}
            </div>

            <div className="space-y-4">
              <div>
                <h3 className="text-sm font-semibold text-zinc-900">Operational details</h3>
                <p className="mt-1 text-sm leading-6 text-zinc-500">Retained for support and debugging, but moved below the primary project narrative.</p>
              </div>
              <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm">
                <div className="grid gap-3 sm:grid-cols-3">
                  {operationalDetails.map((item) => (
                    <div key={item.label} className="rounded-2xl border border-zinc-200 bg-zinc-50 px-3 py-3">
                      <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-zinc-500">{item.label}</div>
                      <div className="mt-1 text-xl font-semibold text-zinc-950">{item.value}</div>
                    </div>
                  ))}
                </div>
                <div className="mt-4 space-y-3 text-sm text-zinc-600">
                  {deliveryIntegrity?.blockingReason ? <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-amber-900"><span className="font-medium">Delivery hold:</span> {deliveryIntegrity.blockingReason}</div> : null}
                  {deliveryIntegrity?.pendingProvisioningReason ? <div className="rounded-2xl border border-sky-200 bg-sky-50 px-4 py-3 text-sky-900"><span className="font-medium">Repo provisioning:</span> {deliveryIntegrity.pendingProvisioningReason}</div> : null}
                  {visibleAttachmentProcessingState ? (
                    <div className={cn("rounded-2xl border px-4 py-3", attachmentProcessingTone)}>
                      <div className="flex flex-wrap items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em]">
                        <span>{visibleAttachmentProcessingState.label || "Attachment processing"}</span>
                        {visibleAttachmentProcessingState.fileCount ? <span>· {visibleAttachmentProcessingState.fileCount} file{visibleAttachmentProcessingState.fileCount === 1 ? "" : "s"}</span> : null}
                      </div>
                      <p className="mt-1 text-sm leading-6">{visibleAttachmentProcessingState.error || visibleAttachmentProcessingState.detail || "Attached materials are still being processed."}</p>
                      {visibleAttachmentProcessingState.updatedAt ? <p className="mt-1 text-xs text-current/70">{formatRelativeTimestamp(visibleAttachmentProcessingState.updatedAt)}</p> : null}
                    </div>
                  ) : null}
                  {exceptionalQueuedHoldReasons.length ? (
                    <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-amber-950">
                      <div className="text-xs font-semibold uppercase tracking-[0.14em] text-amber-700">Needs attention</div>
                      <ul className="mt-2 space-y-2 text-xs leading-5">
                        {exceptionalQueuedHoldReasons.map((reason) => {
                          const shortDetail = reason.status === "waiting_for_approval"
                            ? `${reason.label}. This phase cannot start until approval is complete.`
                            : reason.status === "waiting_for_repo"
                              ? `${reason.label}. Required repo setup is still incomplete.`
                              : reason.status === "waiting_for_worker_capacity"
                                ? `${reason.label}. The assigned owner is still busy with active work.`
                                : reason.detail;

                          return (
                            <li key={reason.taskId}>
                              <span className="font-medium">{reason.taskTitle}</span>: {shortDetail}
                            </li>
                          );
                        })}
                      </ul>
                    </div>
                  ) : null}
                  {stuckWorkflowGuardrail ? <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-amber-900"><span className="font-medium">Workflow guardrail:</span> {stuckWorkflowGuardrail.detail}</div> : null}
                  {queuedPhaseHoldSummary ? <div className="rounded-2xl border border-zinc-200 bg-zinc-50 px-4 py-3"><span className="font-medium text-zinc-900">Phase sequencing:</span> {queuedPhaseHoldSummary}</div> : null}
                  <div className="text-xs text-zinc-400">Last updated {updatedLabel}</div>
                </div>
              </div>
            </div>
          </div>
        </Section>

      </div>

      <StructuredTaskModal
        open={showTaskModal && !selectedTask}
        onClose={() => setShowTaskModal(false)}
        onCreate={handleCreateTask}
        creating={creatingTask}
        milestones={milestones}
        tasks={tasks}
      />
    </div>
  );
}
