"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  Activity,
  ArrowLeft,
  ArrowUpRight,
  CheckCircle2,
  Clock3,
  FileText,
  FolderKanban,
  PauseCircle,
  PlayCircle,
  Plus,
  ShieldCheck,
  Sparkles,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { PageHero, PageHeroStat } from "@/components/ui/page-hero";
import { BrandedEmptyState } from "@/components/ui/branded-empty-state";
import { ProjectTypeBadge } from "@/components/ui/project-badges";
import { formatRelativeTimestamp, getExecutionTone, ProgressRing } from "@/components/ui/execution-visibility";
import {
  formatIntakeValue,
  getReadinessOption,
  getRoutingSummary,
} from "@/lib/project-intake";
import { getProjectStatusTone } from "@/lib/project-ui";
import { resolveProjectDetailRecentUpdates } from "@/lib/project-detail-truth";
import { getProjectLinkEntries, getProjectLinkSuggestions, PROJECT_LINK_FIELDS, PROJECT_LINK_LABELS, type ProjectLinks } from "@/lib/project-links";
import { parseGitHubRepoUrl, type GitHubRepoBinding, type GitHubRepoProvenance } from "@/lib/github-repo-binding";
import { StructuredTaskModal, type StructuredTaskPayload } from "@/components/project/structured-task-modal";
import { TASK_TYPE_CONFIG } from "@/lib/task-model";
import { getBootstrapSprintIds, matchesBootstrapTruth } from "@/lib/project-bootstrap";
import { useRealtimeStore } from "@/lib/realtime-store";
import { cn } from "@/lib/utils";

type ProjectDocument = {
  id: string;
  type: string;
  title: string;
  url?: string | null;
  storage_path?: string | null;
  mime_type?: string | null;
  size_bytes?: number | null;
  created_at: string;
};

type Milestone = {
  id: string;
  name: string;
  goal?: string | null;
  status: string;
  phaseKey?: string | null;
  phaseOrder?: number | null;
  autoGenerated?: boolean;
  category?: "bootstrap" | "delivery";
  approvalGateRequired?: boolean;
  approvalGateStatus?: string;
  totalTasks: number;
  doneTasks: number;
  queuedTasks?: number;
  runningTasks?: number;
  blockedTasks?: number;
  hiddenBootstrapTasks?: number;
  progressPct: number;
  reviewRequest?: {
    id: string;
    status: string;
    summary?: string | null;
    createdAt: string;
    links?: ProjectLinks | null;
  } | null;
};

type ProjectDetail = {
  deliveryIntegrity?: {
    requiresGitHubRepo?: boolean;
    hasGitHubRepo?: boolean;
    pendingProvisioning?: boolean;
    pendingProvisioningReason?: string | null;
    blockingReason?: string | null;
    completionBlocked?: boolean;
    completionCapPct?: number | null;
  };
  project: {
    name: string;
    status: string;
    type?: string | null;
    progress_pct: number;
    intake_summary?: string | null;
    updated_at: string;
    description?: string | null;
    intake?: any;
    links?: ProjectLinks | null;
    github_repo_binding?: GitHubRepoBinding | null;
    github_repo_provenance?: GitHubRepoProvenance | null;
    [key: string]: any;
  };
  teams: any[];
  milestones: Milestone[];
  tasks: any[];
  events: any[];
  recentSignals?: Array<{
    id: string;
    kind: "blocked" | "approval" | "completed" | "progress" | "activity";
    title: string;
    detail: string;
    timestamp: string;
    actorName?: string | null;
  }>;
  truth?: {
    progressPct: number;
    headline: string;
    summary: string;
    execution: {
      key: string;
      label: string;
      description: string;
    };
    counts: {
      delivery: { total: number; queued: number; running: number; done: number; blocked: number };
      bootstrap: { total: number; queued: number; running: number; done: number; blocked: number };
      all: { total: number };
      jobs: { queued: number; running: number; blocked: number };
    };
  };
  executionVisibility?: {
    queuedReasons?: Array<{
      taskId: string;
      taskTitle: string;
      sprintId?: string | null;
      status: string;
      label: string;
      detail: string;
    }>;
  };
  stats: {
    totalTasks: number;
    doneTasks: number;
    queuedTasks?: number;
    blockedTasks: number;
    inProgressTasks: number;
    bootstrapTasks?: number;
    pendingApprovals?: number;
  };
};

function TaskStatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    todo: "border-zinc-200 bg-zinc-100 text-zinc-600",
    in_progress: "border-blue-200 bg-blue-100 text-blue-700",
    review: "border-purple-200 bg-purple-100 text-purple-700",
    done: "border-emerald-200 bg-emerald-100 text-emerald-700",
    blocked: "border-red-200 bg-red-100 text-red-700",
    cancelled: "border-slate-200 bg-slate-100 text-slate-600",
  };
  return (
    <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em]", styles[status] || styles.todo)}>
      {status.replace("_", " ")}
    </span>
  );
}

function SignalBadge({ kind }: { kind: string }) {
  const styles: Record<string, string> = {
    blocked: "border-red-200 bg-red-100 text-red-700",
    approval: "border-amber-200 bg-amber-100 text-amber-700",
    completed: "border-emerald-200 bg-emerald-100 text-emerald-700",
    progress: "border-blue-200 bg-blue-100 text-blue-700",
    activity: "border-zinc-200 bg-zinc-100 text-zinc-700",
  };
  return <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em]", styles[kind] || styles.activity)}>{kind}</span>;
}

function formatReviewStatus(value?: string | null) {
  if (!value || value === "not_requested") return "No review started";
  return value.replace(/_/g, " ");
}

function taskProgressValue(task: any) {
  return typeof task?.progress_pct === "number" && Number.isFinite(task.progress_pct) ? task.progress_pct : 0;
}

function isBootstrapTask(task: any, bootstrapSprintIds?: ReadonlySet<string>) {
  return matchesBootstrapTruth(task, bootstrapSprintIds);
}

function formatBytes(value?: number | null) {
  if (!value) return null;
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${Math.round(value / 1024)} KB`;
  return `${(value / (1024 * 1024)).toFixed(1)} MB`;
}

function artifactEmptyState(projectType?: string | null, intake?: any) {
  if (intake?.shape === "launch-campaign" || ["marketing_growth", "marketing"].includes(projectType || "")) {
    return "No campaign links or creative artifacts added yet.";
  }
  if (["product_build", "ops_enablement", "saas", "web_app", "native_app"].includes(projectType || "")) {
    return "No repo, environment, or build links added yet.";
  }
  return "No project links or artifacts added yet.";
}

function formatUpdatedDate(value?: string | null) {
  if (!value) return "Recently updated";

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Recently updated";

  return `Updated ${date.toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
  })}`;
}

type MilestoneReviewState = {
  tone: "neutral" | "purple" | "amber" | "emerald";
  eyebrow: string;
  title: string;
  description: string;
  helper?: string;
  ctaLabel?: string;
  ctaHref?: string;
};

function EmptySectionState({ icon, title, description, action }: { icon: ReactNode; title: string; description: string; action?: ReactNode }) {
  return <BrandedEmptyState icon={icon} title={title} description={description} action={action} className="border-zinc-200 bg-zinc-50 py-12" />;
}

function getMilestoneReviewState(input: {
  milestone: Milestone;
  reviewTasks: Array<{ id: string; title: string; status: string; review_status?: string | null }>;
}) : MilestoneReviewState {
  const { milestone, reviewTasks } = input;
  const reviewTasksReady = milestone.totalTasks > 0 && milestone.doneTasks === milestone.totalTasks;
  const missingReviewRequestRecord = milestone.approvalGateRequired && milestone.approvalGateStatus === "pending" && !milestone.reviewRequest;
  const milestoneApproved = milestone.approvalGateRequired && milestone.approvalGateStatus === "approved";

  if (milestone.reviewRequest) {
    return {
      tone: "amber",
      eyebrow: "Review request live",
      title: milestone.reviewRequest.summary || "Approval requested",
      description: "A live approval request is open for this milestone. Use the exact linked approval to review and record the decision.",
      helper: reviewTasks.length > 0
        ? `${reviewTasks.length} review task${reviewTasks.length === 1 ? " is" : "s are"} attached to this request.`
        : "This review request is ready in approvals even if the related review-task row is sparse.",
      ctaLabel: "Open linked approval →",
      ctaHref: `/approvals?approval=${milestone.reviewRequest.id}#approval-${milestone.reviewRequest.id}`,
    };
  }

  if (!milestone.approvalGateRequired) {
    return {
      tone: "neutral",
      eyebrow: "Execution milestone",
      title: "Review gate not required",
      description: "This milestone tracks delivery progress without creating an approval handoff.",
      helper: milestone.totalTasks > 0
        ? `${milestone.doneTasks} of ${milestone.totalTasks} task${milestone.totalTasks === 1 ? "" : "s"} completed.`
        : "Add tasks when this phase has concrete work to track.",
    };
  }

  if (milestone.totalTasks === 0) {
    return {
      tone: "neutral",
      eyebrow: "Review gated",
      title: "No milestone tasks yet",
      description: "This milestone is configured for review, but it needs at least one task before a review request can exist.",
      helper: "Add the deliverables for this phase, then finish them to unlock review.",
    };
  }

  if (missingReviewRequestRecord) {
    return {
      tone: "amber",
      eyebrow: "Review handoff needs attention",
      title: "Pending review is missing its approval row",
      description: "This milestone says review is pending, but there is no live approval record yet. Request review again to repair the stuck handoff.",
      helper: reviewTasks.length > 0
        ? `${reviewTasks.length} review task${reviewTasks.length === 1 ? " is" : "s are"} already marked for review.`
        : "The milestone is stuck between completion and approvals.",
    };
  }

  if (milestoneApproved) {
    return {
      tone: "emerald",
      eyebrow: "Review approved",
      title: "Milestone review is finalized",
      description: "This milestone has already been approved, so no new review request is needed.",
      helper: reviewTasks.length > 0
        ? `${reviewTasks.length} review task${reviewTasks.length === 1 ? " was" : "s were"} part of the approved handoff.`
        : reviewTasksReady
          ? "All milestone work is complete and the approval gate is already cleared."
          : `${milestone.doneTasks} of ${milestone.totalTasks} task${milestone.totalTasks === 1 ? "" : "s"} are marked complete while the approval gate remains approved.`,
    };
  }

  if (reviewTasks.length > 0 && !milestone.reviewRequest) {
    return reviewTasksReady
      ? {
          tone: "purple",
          eyebrow: "Review deliverables ready",
          title: "Review tasks exist, but no request has been sent",
          description: "The deliverables for review are ready. Capture the key links below and send the review request to create the approval handoff.",
          helper: `${reviewTasks.length} review task${reviewTasks.length === 1 ? " is" : "s are"} waiting for a real review request.`,
        }
      : {
          tone: "neutral",
          eyebrow: "Review deliverables identified",
          title: "Review is not unlocked yet",
          description: "This milestone already has review tasks, but the milestone still has open delivery work before a request can be sent.",
          helper: `${milestone.doneTasks} of ${milestone.totalTasks} task${milestone.totalTasks === 1 ? "" : "s"} completed before review can start.`,
        };
  }

  if (!reviewTasksReady) {
    return {
      tone: "neutral",
      eyebrow: "Review gated",
      title: "Review is not unlocked yet",
      description: "Finish this milestone's tasks before creating a review request.",
      helper: `${milestone.doneTasks} of ${milestone.totalTasks} task${milestone.totalTasks === 1 ? "" : "s"} completed.`,
    };
  }

  return {
    tone: "purple",
    eyebrow: "Ready for review",
    title: "Milestone complete and ready to request review",
    description: "All milestone work is done. Add the supporting links below and send the review request to create the approval handoff.",
    helper: "Requesting review will preserve the exact approval deep link for this milestone.",
  };
}

function Section({ title, description, children, className, action }: { title: string; description?: string; children: ReactNode; className?: string; action?: ReactNode }) {
  return (
    <Card variant="soft" className={cn("overflow-hidden rounded-[24px] border-zinc-200/90", className)}>
      <CardContent className="p-5 sm:p-6">
        <div className="mb-5 flex items-start justify-between gap-3">
          <div>
            <h2 className="text-lg font-semibold tracking-tight text-zinc-950">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-zinc-500">{description}</p> : null}
          </div>
          {action}
        </div>
        {children}
      </CardContent>
    </Card>
  );
}

function MilestoneReviewCard({
  projectId,
  milestone,
  projectLinks,
  reviewTasks,
  onSaved,
}: {
  projectId: string;
  milestone: Milestone;
  projectLinks?: ProjectLinks | null;
  reviewTasks: Array<{ id: string; title: string; status: string; review_status?: string | null }>;
  onSaved: (payload: { links: ProjectLinks | null }) => void;
}) {
  const [draftLinks, setDraftLinks] = useState<ProjectLinks>(projectLinks || milestone.reviewRequest?.links || {});
  const [note, setNote] = useState("");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const reviewTasksReady = milestone.totalTasks > 0 && milestone.doneTasks === milestone.totalTasks;
  const missingReviewRequestRecord = milestone.approvalGateRequired && milestone.approvalGateStatus === "pending" && !milestone.reviewRequest;
  const milestoneApproved = milestone.approvalGateRequired && milestone.approvalGateStatus === "approved";
  const canRequestReview = Boolean(milestone.approvalGateRequired && !milestone.reviewRequest && !milestoneApproved && reviewTasksReady);
  const reviewLinks = getProjectLinkEntries(milestone.reviewRequest?.links || projectLinks || null);
  const reviewState = getMilestoneReviewState({ milestone, reviewTasks });
  const reviewStateStyles = reviewState.tone === "amber"
    ? {
        shell: "border-amber-200 bg-amber-50",
        eyebrow: "text-amber-700",
        title: "text-amber-950",
        body: "text-amber-900",
        helper: "text-amber-800",
        chip: "border-amber-200 bg-white text-amber-800",
      }
    : reviewState.tone === "purple"
      ? {
          shell: "border-purple-100 bg-purple-50/70",
          eyebrow: "text-purple-700",
          title: "text-purple-950",
          body: "text-purple-900",
          helper: "text-purple-800",
          chip: "border-purple-200 bg-white text-purple-800",
        }
      : reviewState.tone === "emerald"
        ? {
            shell: "border-emerald-200 bg-emerald-50/80",
            eyebrow: "text-emerald-700",
            title: "text-emerald-950",
            body: "text-emerald-900",
            helper: "text-emerald-800",
            chip: "border-emerald-200 bg-white text-emerald-800",
          }
        : {
            shell: "border-zinc-200 bg-zinc-50",
            eyebrow: "text-zinc-500",
            title: "text-zinc-900",
            body: "text-zinc-600",
            helper: "text-zinc-500",
            chip: "border-zinc-200 bg-white text-zinc-700",
          };

  useEffect(() => {
    setDraftLinks(projectLinks || milestone.reviewRequest?.links || {});
  }, [projectLinks, milestone.reviewRequest?.links]);

  const requestReview = async () => {
    setSaving(true);
    setMessage(null);
    try {
      const res = await fetch(`/api/projects/${projectId}/review-requests`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sprintId: milestone.id, note, links: draftLinks }),
      });
      const payload = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(payload.error || "Failed to request review");
      onSaved({ links: payload.links || null });
      setMessage("Review requested");
    } catch (e: any) {
      setMessage(e.message || "Failed to request review");
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-sm font-semibold text-zinc-900">{milestone.name}</p>
            <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em] text-zinc-600">{milestone.progressPct}% complete</span>
            <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em]", milestone.category === "bootstrap" ? "border-sky-200 bg-sky-50 text-sky-700" : "border-red-200 bg-red-50 text-red-700")}>{milestone.category === "bootstrap" ? "Kickoff setup" : "Active work"}</span>
            {milestone.approvalGateRequired ? <span className="rounded-full border border-purple-100 bg-purple-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.12em] text-purple-700">Review gate</span> : null}
          </div>
          {milestone.goal ? <p className="mt-2 text-sm leading-6 text-zinc-600">{milestone.goal}</p> : null}
          <p className="mt-2 text-xs leading-5 text-zinc-500">
            {milestone.doneTasks} of {milestone.totalTasks} {milestone.category === "bootstrap" ? "kickoff" : "active"} task{milestone.totalTasks === 1 ? "" : "s"} complete · {milestone.queuedTasks || 0} queued · {milestone.runningTasks || 0} in progress · {milestone.blockedTasks || 0} blocked
            {milestone.hiddenBootstrapTasks ? ` · ${milestone.hiddenBootstrapTasks} kickoff task${milestone.hiddenBootstrapTasks === 1 ? "" : "s"} hidden from active-work totals` : ""}
          </p>
        </div>
        <TaskStatusBadge status={milestone.status === "active" ? "in_progress" : milestone.status === "completed" ? "done" : milestone.status === "blocked" ? "blocked" : "todo"} />
      </div>

      <div className={cn("mt-4 rounded-2xl border p-4", reviewStateStyles.shell)}>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <div className={cn("text-[11px] font-medium uppercase tracking-[0.14em]", reviewStateStyles.eyebrow)}>{reviewState.eyebrow}</div>
            <p className={cn("mt-1 text-sm font-medium", reviewStateStyles.title)}>{reviewState.title}</p>
            <p className={cn("mt-2 text-sm leading-6", reviewStateStyles.body)}>{reviewState.description}</p>
          </div>
          {reviewState.ctaHref && reviewState.ctaLabel ? (
            <Link href={reviewState.ctaHref} className="text-sm font-medium text-red-700 hover:text-red-800">{reviewState.ctaLabel}</Link>
          ) : null}
        </div>

        {reviewTasks.length > 0 ? (
          <ul className={cn("mt-3 space-y-2 text-sm", reviewStateStyles.body)}>
            {reviewTasks.map((task) => (
              <li key={task.id} className="flex items-start gap-2">
                <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" />
                <span>
                  {task.title}
                  <span className="ml-2 text-xs opacity-80">({formatReviewStatus(task.review_status)})</span>
                </span>
              </li>
            ))}
          </ul>
        ) : null}

        {reviewLinks.length > 0 ? (
          <div className="mt-3 flex flex-wrap gap-2">
            {reviewLinks.map((link) => (
              <a key={link.key} href={link.url} target="_blank" rel="noreferrer" className={cn("inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-medium", reviewStateStyles.chip)}>
                {link.label}
                <ArrowUpRight className="h-3.5 w-3.5" />
              </a>
            ))}
          </div>
        ) : null}

        {reviewState.helper ? <p className={cn("mt-3 text-xs leading-5", reviewStateStyles.helper)}>{reviewState.helper}</p> : null}
      </div>

      {canRequestReview ? (
        <details className="mt-4 rounded-2xl border border-zinc-200 bg-zinc-50 p-4" open>
          <summary className="cursor-pointer list-none text-sm font-medium text-zinc-900">{missingReviewRequestRecord ? "Repair and request review" : "Request review"}</summary>
          <p className="mt-2 text-sm leading-6 text-zinc-500">Capture artifact links for this milestone review. Saved links also populate the project Links & artifacts section. Code-heavy phases require a real GitHub repo link before review can start.{missingReviewRequestRecord ? " This will repair the stuck pending-review state and create the actual approvals record." : ""}</p>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            {PROJECT_LINK_FIELDS.map((key) => (
              <label key={key} className="block">
                <span className="mb-1.5 block text-sm font-medium text-zinc-700">{PROJECT_LINK_LABELS[key]} URL</span>
                <input
                  type="url"
                  value={draftLinks[key] || ""}
                  onChange={(e) => setDraftLinks((current) => {
                    const next = { ...current };
                    if (e.target.value.trim()) next[key] = e.target.value;
                    else delete next[key];
                    return next;
                  })}
                  className="w-full rounded-xl border border-zinc-300 bg-white px-3 py-2 text-sm focus:border-red-500 focus:outline-none"
                  placeholder={`https://${key === "github" ? "github.com/org/repo" : "example.com"}`}
                />
              </label>
            ))}
          </div>
          <div className="mt-3">
            <label className="block text-sm font-medium text-zinc-700">Review note</label>
            <textarea value={note} onChange={(e) => setNote(e.target.value)} rows={3} placeholder="What's ready for review?" className="mt-1 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2 text-sm focus:border-red-500 focus:outline-none" />
          </div>
          <div className="mt-4 flex items-center justify-between gap-3">
            {message ? <p className={cn("text-xs", message === "Review requested" ? "text-emerald-600" : "text-zinc-500")}>{message}</p> : <span />}
            <Button onClick={requestReview} disabled={saving} variant="warm" className="rounded-xl px-4">{saving ? "Requesting..." : missingReviewRequestRecord ? "Repair & request review" : "Request review"}</Button>
          </div>
        </details>
      ) : null}
    </div>
  );
}

function LinkEditor({
  projectId,
  projectType,
  intake,
  links,
  githubBinding,
  onSaved,
}: {
  projectId: string;
  projectType?: string | null;
  intake?: any;
  links?: ProjectLinks | null;
  githubBinding?: GitHubRepoBinding | null;
  onSaved: (payload: { links: ProjectLinks | null; githubBinding: GitHubRepoBinding | null }) => void;
}) {
  const [draft, setDraft] = useState<ProjectLinks>(links || {});
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const suggestedFields = useMemo(() => getProjectLinkSuggestions(projectType, intake), [projectType, intake]);
  const parsedGithubRepo = useMemo(() => parseGitHubRepoUrl(draft.github), [draft.github]);

  useEffect(() => {
    setDraft(links || {});
  }, [links]);

  const orderedFields = useMemo(() => {
    const used = PROJECT_LINK_FIELDS.filter((key) => Boolean(draft[key]));
    const suggestedUnused = suggestedFields.filter((key) => !used.includes(key));
    const remaining = PROJECT_LINK_FIELDS.filter((key) => !used.includes(key) && !suggestedUnused.includes(key));
    return [...used, ...suggestedUnused, ...remaining];
  }, [draft, suggestedFields]);

  const handleSave = async () => {
    setSaving(true);
    setMessage(null);
    try {
      const res = await fetch(`/api/projects/${projectId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ links: draft, githubRepo: draft.github ? { url: draft.github } : null }),
      });
      const payload = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(payload.error || "Failed to save links");
      onSaved({ links: payload.project?.links || null, githubBinding: payload.project?.github_repo_binding || null });
      setMessage("Saved");
    } catch (e: any) {
      setMessage(e.message || "Failed to save links");
    } finally {
      setSaving(false);
    }
  };

  return (
    <details className="group rounded-2xl border border-zinc-200 bg-zinc-50" open={Boolean(Object.keys(draft || {}).length === 0)}>
      <summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 text-sm font-medium text-zinc-900">
        <span>Edit project links</span>
        <span className="text-xs text-zinc-400 transition group-open:rotate-180">⌄</span>
      </summary>
      <div className="space-y-4 border-t border-zinc-200 px-4 py-4">
        <div className="flex flex-wrap gap-2">
          {suggestedFields.map((key) => (
            <span key={key} className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[11px] font-medium text-red-700">Suggested: {PROJECT_LINK_LABELS[key]}</span>
          ))}
        </div>

        {(githubBinding || parsedGithubRepo) ? (
          <div className="rounded-2xl border border-zinc-200 bg-white p-4 text-sm text-zinc-600">
            <div className="text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-400">GitHub repo binding</div>
            <div className="mt-1 font-medium text-zinc-900">{githubBinding?.fullName || parsedGithubRepo?.fullName}</div>
            <p className="mt-1 leading-6">{githubBinding ? "Project-level repo binding is live and synced from the GitHub link below." : "Saving this GitHub URL will create a first-class repo binding for this project."}</p>
          </div>
        ) : null}

        <div className="grid gap-3 sm:grid-cols-2">
          {orderedFields.map((key) => (
            <label key={key} className="block">
              <span className="mb-1.5 block text-sm font-medium text-zinc-700">{PROJECT_LINK_LABELS[key]} URL</span>
              <input
                type="url"
                value={draft[key] || ""}
                onChange={(e) => {
                  const value = e.target.value;
                  setDraft((current) => {
                    const next = { ...current };
                    if (value.trim()) next[key] = value;
                    else delete next[key];
                    return next;
                  });
                  setMessage(null);
                }}
                className="w-full rounded-xl border border-zinc-300 bg-white px-3 py-2 text-sm focus:border-red-500 focus:outline-none"
                placeholder={`https://${key === "github" ? "github.com/org/repo" : key === "preview" ? "preview.example.com" : key === "production" ? "app.example.com" : key === "docs" ? "docs.example.com" : key === "figma" ? "figma.com/file/..." : "admin.example.com"}`}
              />
            </label>
          ))}
        </div>

        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          {message ? <p className={cn("text-xs", message === "Saved" ? "text-emerald-600" : "text-zinc-500")}>{message}</p> : <span />}
          <Button onClick={handleSave} disabled={saving} variant="warm" className="rounded-xl px-4">
            {saving ? "Saving..." : "Save project links"}
          </Button>
        </div>
      </div>
    </details>
  );
}

export default function ProjectDetailPage() {
  const params = useParams();
  const projectId = params.id as string;
  const agentsById = useRealtimeStore((s) => s.agentsById);
  const projectsById = useRealtimeStore((s) => s.projectsById);
  const approvalsById = useRealtimeStore((s) => s.approvalsById);
  const jobsById = useRealtimeStore((s) => s.jobsById);
  const storeEvents = useRealtimeStore((s) => s.events);

  const [data, setData] = useState<ProjectDetail | null>(null);
  const [documents, setDocuments] = useState<ProjectDocument[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [showTaskModal, setShowTaskModal] = useState(false);
  const [selectedTask, setSelectedTask] = useState<any>(null);
  const [creatingTask, setCreatingTask] = useState(false);
  const [taskDesc, setTaskDesc] = useState("");

  const fetchProject = useCallback(async (showSpinner = false) => {
    if (showSpinner) setLoading(true);
    try {
      const [projectRes, docsRes] = await Promise.all([
        fetch(`/api/projects/${projectId}`, { cache: "no-store" }),
        fetch(`/api/projects/${projectId}/documents`, { cache: "no-store" }),
      ]);

      if (!projectRes.ok) {
        const err = await projectRes.json().catch(() => ({ error: "Failed to load project" }));
        throw new Error(err.error || "Failed to load project");
      }

      const json = await projectRes.json();
      setData(json);

      if (docsRes.ok) {
        const docsJson = await docsRes.json();
        setDocuments(docsJson.documents || []);
      } else {
        setDocuments([]);
      }

      setError(null);
    } catch (e: any) {
      setError(e.message || "Failed to load project");
    } finally {
      if (showSpinner) setLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    if (projectId) fetchProject(true);
  }, [projectId, fetchProject]);

  useEffect(() => {
    if (!projectId) return;

    let cancelled = false;

    const tick = async () => {
      if (cancelled || document.visibilityState !== "visible" || !navigator.onLine) return;
      await fetchProject(false);
    };

    const interval = window.setInterval(tick, 15000);
    const onVisible = () => {
      if (document.visibilityState === "visible") void tick();
    };

    document.addEventListener("visibilitychange", onVisible);
    window.addEventListener("online", onVisible);

    return () => {
      cancelled = true;
      window.clearInterval(interval);
      document.removeEventListener("visibilitychange", onVisible);
      window.removeEventListener("online", onVisible);
    };
  }, [projectId, fetchProject]);

  const realtimeRefreshKey = useMemo(() => {
    const realtimeProject = projectsById.get(projectId);
    const realtimeEvents = storeEvents.filter((event) => event.project_id === projectId);
    const realtimeApprovals = Array.from(approvalsById.values()).filter((approval) => approval.project_id === projectId);
    const realtimeJobs = Array.from(jobsById.values()).filter((job) => job.project_id === projectId);

    const projectUpdatedAt = realtimeProject?.updated_at || "";
    const latestEventTs = realtimeEvents[0]?.timestamp || "";
    const approvalsKey = realtimeApprovals
      .map((approval) => `${approval.id}:${approval.status}:${approval.created_at}`)
      .sort()
      .join("|");
    const jobsKey = realtimeJobs
      .map((job) => `${job.id}:${job.status}`)
      .sort()
      .join("|");

    return [projectUpdatedAt, latestEventTs, approvalsKey, jobsKey].join("::");
  }, [approvalsById, jobsById, projectId, projectsById, storeEvents]);

  useEffect(() => {
    if (!projectId || loading || !data) return;
    if (!realtimeRefreshKey) return;

    const timeout = window.setTimeout(() => {
      if (document.visibilityState === "visible" && navigator.onLine) {
        void fetchProject(false);
      }
    }, 250);

    return () => window.clearTimeout(timeout);
  }, [projectId, loading, data, realtimeRefreshKey, fetchProject]);

  const handleStatusChange = async (newStatus: string) => {
    setActionLoading(newStatus);
    setError(null);
    setData((prev) => (prev ? { ...prev, project: { ...prev.project, status: newStatus, updated_at: new Date().toISOString() } } : prev));

    try {
      const res = await fetch(`/api/projects/${projectId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus }),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || "Failed to update");
      setData((prev) => (prev ? { ...prev, project: { ...prev.project, ...json.project } } : prev));
    } catch (e: any) {
      setError(e.message || "Failed to update");
      await fetchProject(false);
    } finally {
      setActionLoading(null);
    }
  };

  const handleDelete = async () => {
    setActionLoading("delete");
    try {
      const res = await fetch(`/api/projects/${projectId}`, { method: "DELETE" });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || "Failed to delete");
      window.location.href = "/projects";
    } catch (e: any) {
      setError(e.message);
    } finally {
      setActionLoading(null);
      setShowDeleteConfirm(false);
    }
  };

  const handleCreateTask = async (payload: StructuredTaskPayload) => {
    setCreatingTask(true);
    try {
      const res = await fetch(`/api/projects/${projectId}/tasks`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const json = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(json.error || "Failed to create task");
      setShowTaskModal(false);
      await fetchProject(false);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setCreatingTask(false);
    }
  };

  const handleUpdateTask = async () => {
    if (!selectedTask) return;
    try {
      const res = await fetch(`/api/projects/${projectId}/tasks/${selectedTask.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ notes: taskDesc, status: selectedTask.status }),
      });
      if (!res.ok) throw new Error("Failed to save task");
      setShowTaskModal(false);
      await fetchProject(false);
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleDeleteTask = async () => {
    if (!selectedTask) return;
    try {
      const res = await fetch(`/api/projects/${projectId}/tasks/${selectedTask.id}`, {
        method: "DELETE",
      });
      if (!res.ok) throw new Error("Failed to delete task");
      setShowTaskModal(false);
      await fetchProject(false);
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleTaskClick = (task: any) => {
    setSelectedTask(task);
    setTaskDesc(task.description || "");
    setShowTaskModal(true);
  };

  const taskGroups = useMemo(() => {
    const list = data?.tasks || [];
    return {
      todo: list.filter((task: any) => task.status === "todo"),
      inProgress: list.filter((task: any) => task.status === "in_progress" || task.status === "review"),
      done: list.filter((task: any) => task.status === "done"),
      blocked: list.filter((task: any) => task.status === "blocked"),
    };
  }, [data?.tasks]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 p-12">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-red-200 border-t-red-600" />
        <div className="text-zinc-500">Loading project…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6">
        <Card className="rounded-[24px] border-red-200 bg-red-50 shadow-sm">
          <CardContent className="py-6">
            <div className="flex items-center gap-2 font-medium text-red-700">
              <span className="text-xl">⚠️</span>
              <p>Error loading project</p>
            </div>
            <p className="mt-2 text-sm text-red-600">{error}</p>
            <div className="mt-4 flex gap-3">
              <Button onClick={() => fetchProject(true)} variant="destructive" className="rounded-xl">Retry</Button>
              <Link href="/projects" className="inline-flex items-center rounded-xl border border-zinc-300 px-4 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50">
                ← Back to Projects
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!data?.project) {
    return null;
  }

  const { project, teams, milestones = [], tasks, recentSignals = [], events = [], stats, deliveryIntegrity, truth, executionVisibility } = data;
  const bootstrapSprintIds = getBootstrapSprintIds(milestones.map((milestone) => ({ id: milestone.id, auto_generated: milestone.autoGenerated, phase_key: milestone.phaseKey })));
  const intake = project.intake || null;
  const routing = intake ? getRoutingSummary(intake) : null;
  const projectLinks = getProjectLinkEntries(project.links);
  const summaryText = project.intake_summary || project.description || intake?.summary || null;
  const hasBrief = Boolean(routing || intake || summaryText);
  const actionTargetStatus = project.status === "active" ? "paused" : project.status === "paused" ? "active" : null;
  const actionLabel = actionTargetStatus === "paused" ? "Pause" : actionTargetStatus === "active" ? "Resume" : null;
  const isStatusActionLoading = actionTargetStatus ? actionLoading === actionTargetStatus : false;
  const statusTone = getProjectStatusTone(project.status);
  const progress = Math.max(0, Math.min(100, truth?.progressPct ?? project.progress_pct ?? 0));
  const displayedRecentUpdates = resolveProjectDetailRecentUpdates({ recentSignals, events });
  const briefFacts = [
    intake?.shape ? { label: "Shape", value: formatIntakeValue(intake.shape) } : null,
    intake ? { label: "Readiness", value: getReadinessOption(intake.stage, intake.confidence)?.label || formatIntakeValue(intake.stage) } : null,
    intake?.confidence ? { label: "Confidence", value: formatIntakeValue(intake.confidence) } : null,
    routing?.ownerTeam ? { label: "Primary route", value: routing.ownerTeam } : null,
    routing?.qcTeam ? { label: "QC", value: routing.qcTeam } : null,
  ].filter(Boolean) as Array<{ label: string; value: string }>;
  const contextChips = (intake?.context || []) as string[];
  const capabilityChips = (intake?.capabilities || []) as string[];

  const executionSummary = truth?.execution ?? { key: "idle", label: statusTone.label, description: "No project work is visible yet." };
  const executionBadgeTone =
    executionSummary.key === "blocked"
      ? "border-red-200 bg-red-50 text-red-700"
      : executionSummary.key === "running"
        ? "border-blue-200 bg-blue-50 text-blue-700"
        : executionSummary.key === "completed"
          ? "border-emerald-200 bg-emerald-50 text-emerald-700"
          : executionSummary.key === "planning_running"
            ? "border-sky-200 bg-sky-50 text-sky-700"
            : executionSummary.key === "planning_queued" || executionSummary.key === "queued"
              ? "border-zinc-200 bg-zinc-50 text-zinc-700"
              : "border-amber-200 bg-amber-50 text-amber-700";
  const operationalDetails = [
    { label: "Pending approvals", value: String(stats.pendingApprovals || 0) },
    { label: "Queued jobs", value: String(truth?.counts.jobs.queued ?? truth?.counts.delivery.queued ?? 0) },
    { label: "Running now", value: String(truth?.counts.jobs.running ?? truth?.counts.delivery.running ?? 0) },
    { label: "Updated", value: formatUpdatedDate(project.updated_at) },
  ];

  const workSummary = [
    `${truth?.counts.delivery.done ?? stats.doneTasks} done`,
    `${truth?.counts.delivery.blocked ?? stats.blockedTasks} blocked`,
    `${truth?.counts.delivery.total ?? stats.totalTasks} total items`,
    `${truth?.counts.bootstrap.total ?? (stats.bootstrapTasks || 0)} kickoff tasks`,
  ].join(" • ");

  return (
    <div className="min-w-0 space-y-6 overflow-x-hidden pb-10 md:space-y-8">
      {showDeleteConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
          <div className="w-full max-w-md rounded-[24px] bg-white p-6 shadow-xl">
            <h3 className="text-lg font-semibold text-zinc-900">Delete this project?</h3>
            <p className="mt-2 text-sm text-zinc-600">This cannot be undone.</p>
            <div className="mt-4 flex gap-3">
              <Button onClick={() => setShowDeleteConfirm(false)} variant="outline" className="flex-1 rounded-xl">Cancel</Button>
              <Button onClick={handleDelete} disabled={actionLoading === "delete"} variant="destructive" className="flex-1 rounded-xl">
                {actionLoading === "delete" ? "Deleting..." : "Delete"}
              </Button>
            </div>
          </div>
        </div>
      )}

      <PageHero>
        <div className="flex flex-col gap-6 p-5 sm:p-6 lg:flex-row lg:items-end lg:justify-between lg:p-8">
          <div className="max-w-3xl space-y-4">
            <div className="flex flex-wrap items-center gap-2">
              <Link href="/projects" className="inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-white px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-700 transition hover:border-red-200 hover:text-red-700">
                <ArrowLeft className="h-3.5 w-3.5" />
                Back to projects
              </Link>
              <div className="inline-flex items-center gap-2 rounded-full border border-red-200 bg-white px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-red-700">
                <Sparkles className="h-3.5 w-3.5 text-red-500" />
                Project detail
              </div>
            </div>

            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-2">
                {project.type ? <ProjectTypeBadge type={project.type} status={project.status} className="normal-case tracking-normal" /> : null}
              </div>
              <div>
                <h1 className="break-words text-3xl font-semibold tracking-tight text-zinc-950 sm:text-4xl">{project.name}</h1>
                <p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-600 sm:text-base">
                  {summaryText || "Use this page to track project context, active tasks, links, signals, and the teams keeping delivery on course."}
                </p>
              </div>
            </div>

            <div className={cn("rounded-2xl border p-4", statusTone.surface)}>
              {deliveryIntegrity?.blockingReason ? (
                <div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
                  <div className="font-medium">Delivery integrity hold</div>
                  <div className="mt-1 leading-6">{deliveryIntegrity.blockingReason}</div>
                </div>
              ) : deliveryIntegrity?.pendingProvisioningReason ? (
                <div className="mb-4 rounded-2xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-900">
                  <div className="font-medium">GitHub repo provisioning pending</div>
                  <div className="mt-1 leading-6">{deliveryIntegrity.pendingProvisioningReason}</div>
                </div>
              ) : null}
              <div className="flex flex-col gap-4">
                <div className="flex flex-col gap-3">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className={cn("rounded-full border px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.14em]", executionBadgeTone)}>
                      {executionSummary.label}
                    </span>
                    <span className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Authoritative delivery status</span>
                  </div>
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
                    <div>
                      <p className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Delivery progress</p>
                      <div className="mt-1 flex flex-wrap items-center gap-3">
                        <p className="text-2xl font-semibold tracking-tight text-zinc-950">{progress}% complete</p>
                        <p className="text-sm text-zinc-600">{truth ? `${truth.headline}. ${executionSummary.description}` : executionSummary.description}</p>
                      </div>
                    </div>
                  </div>
                  {truth ? <p className="max-w-2xl text-sm leading-6 text-zinc-600">{truth.summary}</p> : null}
                </div>

                <div className="rounded-2xl border border-zinc-200 bg-white/80 px-3 py-2.5">
                  <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-zinc-600">
                    {operationalDetails.map((item, index) => (
                      <div key={item.label} className="flex items-center gap-2">
                        {index > 0 ? <span className="hidden text-zinc-300 sm:inline">•</span> : null}
                        <span className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">{item.label}</span>
                        <span className="font-medium text-zinc-900">{item.value}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="rounded-2xl border border-zinc-200 bg-white/70 px-3 py-3 text-sm text-zinc-600">
                  <div className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">Work snapshot</div>
                  <div className="mt-2 font-medium text-zinc-900">{workSummary}</div>
                </div>
              </div>
              <div className={cn("mt-4 h-2.5 overflow-hidden rounded-full", statusTone.progressTrack)}>
                <div className={cn("h-full rounded-full transition-all duration-500", statusTone.progress)} style={{ width: `${progress}%` }} />
              </div>
            </div>
          </div>

          <div className="flex w-full flex-col gap-3 lg:w-auto lg:min-w-[320px] lg:max-w-sm">
            <div className="rounded-2xl border border-zinc-200 bg-white p-4">
              <div className="flex items-center gap-2 text-sm font-medium text-zinc-900">
                <Clock3 className="h-4 w-4 text-red-500" />
                Workspace overview
              </div>
              <p className="mt-1 text-sm leading-6 text-zinc-500">Key context and actions, without repeating the delivery status you already see on the left.</p>

              {executionVisibility?.queuedReasons?.length ? (
                <div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 px-3 py-3 text-amber-950">
                  <div className="text-xs font-semibold uppercase tracking-[0.14em] text-amber-700">What is holding queued work</div>
                  <ul className="mt-2 space-y-2 text-xs leading-5">
                    {executionVisibility.queuedReasons.map((reason) => (
                      <li key={reason.taskId}>
                        <span className="font-medium">{reason.taskTitle}</span>: {reason.detail}
                      </li>
                    ))}
                  </ul>
                </div>
              ) : null}

              <div className="mt-4 border-t border-zinc-200 pt-4">
                <div className="text-sm font-medium text-zinc-900">Project actions</div>
                <p className="mt-1 text-sm leading-6 text-zinc-500">Create tasks, shift delivery state, or remove the project without leaving this workspace.</p>
                <div className="mt-4 grid gap-2">
                  {actionTargetStatus && actionLabel ? (
                    <Button
                      onClick={() => handleStatusChange(actionTargetStatus)}
                      disabled={isStatusActionLoading}
                      variant={actionTargetStatus === "paused" ? "outline" : "secondary"}
                      className="w-full justify-center rounded-xl"
                    >
                      {actionTargetStatus === "paused" ? <PauseCircle className="h-4 w-4" /> : <PlayCircle className="h-4 w-4" />}
                      {isStatusActionLoading ? "Updating..." : actionLabel}
                    </Button>
                  ) : null}
                  <Button onClick={() => { setSelectedTask(null); setShowTaskModal(true); }} size="lg" variant="warm" className="w-full rounded-xl">
                    <Plus className="h-4 w-4" />
                    New task
                  </Button>
                  <Button onClick={() => setShowDeleteConfirm(true)} variant="outline" className="w-full justify-center rounded-xl border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800">
                    <Trash2 className="h-4 w-4" />
                    Delete project
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </PageHero>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]">
        <div className="space-y-4">
          <Section title="Project brief" description="Scope, readiness, and routing context for everyone touching the work.">
            {hasBrief ? (
              <div className="space-y-4">
                {summaryText ? (
                  <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4">
                    <div className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">Summary</div>
                    <p className="mt-2 text-sm leading-6 text-zinc-700">{summaryText}</p>
                  </div>
                ) : null}

                {(routing || briefFacts.length > 0) ? (
                  <div className="grid gap-4 lg:grid-cols-[minmax(0,1.1fr)_minmax(240px,0.9fr)]">
                    {routing ? (
                      <div className="rounded-2xl border border-zinc-200 bg-white p-4">
                        <div className="flex flex-wrap gap-2">
                          <span className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[11px] font-medium text-red-700">Primary route: {routing.ownerTeam}</span>
                          <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[11px] font-medium text-zinc-700">QC: {routing.qcTeam}</span>
                        </div>
                        <p className="mt-3 text-sm leading-6 text-zinc-600">{routing.rationale}</p>
                      </div>
                    ) : null}
                    {briefFacts.length > 0 ? (
                      <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4">
                        <div className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">Quick facts</div>
                        <dl className="mt-3 space-y-2 text-sm">
                          {briefFacts.map((fact) => (
                            <div key={fact.label} className="flex items-start justify-between gap-3">
                              <dt className="text-zinc-500">{fact.label}</dt>
                              <dd className="text-right font-medium text-zinc-900">{fact.value}</dd>
                            </div>
                          ))}
                        </dl>
                      </div>
                    ) : null}
                  </div>
                ) : null}

                {(contextChips.length > 0 || capabilityChips.length > 0) ? (
                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-2xl border border-zinc-200 bg-white p-4">
                      <div className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">Context</div>
                      <div className="mt-2 flex flex-wrap gap-2">
                        {contextChips.length > 0 ? contextChips.map((value) => (
                          <span key={value} className="rounded-full border border-zinc-200 bg-zinc-50 px-2 py-1 text-xs text-zinc-700">{formatIntakeValue(value)}</span>
                        )) : <span className="text-sm text-zinc-500">None selected</span>}
                      </div>
                    </div>
                    <div className="rounded-2xl border border-zinc-200 bg-white p-4">
                      <div className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">Capabilities</div>
                      <div className="mt-2 flex flex-wrap gap-2">
                        {capabilityChips.length > 0 ? capabilityChips.map((value) => (
                          <span key={value} className="rounded-full border border-zinc-200 bg-zinc-50 px-2 py-1 text-xs text-zinc-700">{formatIntakeValue(value)}</span>
                        )) : <span className="text-sm text-zinc-500">None selected</span>}
                      </div>
                    </div>
                  </div>
                ) : null}

                {intake?.goals ? (
                  <div className="rounded-2xl border border-zinc-200 bg-white p-4">
                    <div className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-400">Goals / notes</div>
                    <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-zinc-600">{intake.goals}</p>
                  </div>
                ) : null}
              </div>
            ) : (
              <EmptySectionState
                icon={<FileText className="h-7 w-7" />}
                title="Project brief still needs context"
                description="Add intake details, a short summary, or routing context so everyone has a shared brief before execution ramps up."
              />
            )}
          </Section>

          <Section title="Milestones & review" description="Phases move from execution into a concrete review handoff instead of a placeholder state.">
            {milestones.length === 0 ? (
              <EmptySectionState
                icon={<ShieldCheck className="h-7 w-7" />}
                title="No milestones yet"
                description="Create the first milestone to define phases, unlock review guidance, and make approval handoffs visible on this page."
              />
            ) : (
              <div className="space-y-3">
                {milestones.map((milestone) => (
                  <MilestoneReviewCard
                    key={milestone.id}
                    projectId={projectId}
                    milestone={milestone}
                    reviewTasks={tasks.filter((task: any) => task.sprint_id === milestone.id && task.review_required)}
                    projectLinks={project.links}
                    onSaved={({ links }) => {
                      setData((prev) => {
                        if (!prev) return prev;
                        return {
                          ...prev,
                          project: { ...prev.project, links },
                        };
                      });
                      void fetchProject(false);
                    }}
                  />
                ))}
              </div>
            )}
          </Section>

          <Section title="Task board" description="Keep work moving without opening every task.">
            {truth ? (
              <div className="rounded-2xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm text-zinc-600">
                This board shows what is queued, in progress, blocked, and done. Kickoff setup stays visible, but the headline progress only counts active delivery work.
              </div>
            ) : null}
            {tasks.length === 0 ? (
              <EmptySectionState
                icon={<FolderKanban className="h-7 w-7" />}
                title="No active work yet"
                description="Add the first work item to move this project from setup into execution. The board will update as work moves across lanes."
                action={<Button onClick={() => { setSelectedTask(null); setShowTaskModal(true); }} variant="warm" className="rounded-xl px-4">Create first work item</Button>}
              />
            ) : (
              <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                {[
                  ["Backlog", taskGroups.todo, "border-zinc-200 bg-zinc-50"],
                  ["In flight", taskGroups.inProgress, "border-blue-100 bg-blue-50/60"],
                  ["Blocked", taskGroups.blocked, "border-amber-100 bg-amber-50/70"],
                  ["Done", taskGroups.done, "border-emerald-100 bg-emerald-50/70"],
                ].map(([label, bucket, bucketClass]) => (
                  <div key={String(label)} className={cn("rounded-2xl border p-3", String(bucketClass))}>
                    <div className="mb-3 flex items-center justify-between gap-2">
                      <h3 className="text-sm font-semibold text-zinc-900">{label}</h3>
                      <span className="rounded-full border border-zinc-200 bg-white px-2.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.12em] text-zinc-500">{(bucket as any[]).length}</span>
                    </div>
                    <div className="space-y-2">
                      {(bucket as any[]).length === 0 ? (
                        <div className="rounded-xl border border-dashed border-zinc-200 bg-white px-3 py-4 text-xs text-zinc-400">No items</div>
                      ) : (
                        (bucket as any[]).map((task: any) => {
                          const assignee = task.assignee_agent_id ? agentsById.get(task.assignee_agent_id) : null;
                          const taskTypeConfig = task.task_type ? TASK_TYPE_CONFIG[task.task_type as keyof typeof TASK_TYPE_CONFIG] : null;
                          const executionTone = getExecutionTone({
                            status: task.status,
                            reviewRequired: task.review_required,
                            reviewStatus: task.review_status,
                          });
                          const taskProgress = taskProgressValue(task);
                          return (
                            <button key={task.id} onClick={() => handleTaskClick(task)} className="block w-full rounded-xl border border-zinc-200 bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-red-200">
                              <div className="flex items-start justify-between gap-3">
                                <div className="min-w-0 flex-1">
                                  <div className="flex items-start justify-between gap-2">
                                    <span className="line-clamp-2 text-sm font-medium text-zinc-900">{task.title}</span>
                                    <TaskStatusBadge status={task.status} />
                                  </div>
                                  {taskTypeConfig ? <p className="mt-2 text-[11px] font-medium uppercase tracking-[0.12em] text-red-600">{taskTypeConfig.label}</p> : null}
                                  <div className="mt-2 flex flex-wrap gap-2">
                                    <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em]", executionTone.badgeClassName)}>{executionTone.label}</span>
                                    {isBootstrapTask(task, bootstrapSprintIds) ? <span className="rounded-full border border-sky-200 bg-sky-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-sky-700">Kickoff</span> : <span className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-red-700">Active work</span>}
                                    {task.review_required ? <span className="rounded-full border border-purple-100 bg-purple-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-purple-700">{formatReviewStatus(task.review_status)}</span> : null}
                                  </div>
                                </div>
                                <ProgressRing value={taskProgress} size={48} strokeWidth={4} />
                              </div>
                              {(task.description || assignee || task.updated_at) && (
                                <div className="mt-2 space-y-1">
                                  {task.description && <p className="line-clamp-2 text-xs leading-5 text-zinc-500">{task.description}</p>}
                                  <div className="flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-zinc-400">
                                    {assignee ? <p>Owner: {assignee.name}</p> : null}
                                    {task.updated_at ? <p>{formatRelativeTimestamp(task.updated_at)}</p> : null}
                                  </div>
                                </div>
                              )}
                            </button>
                          );
                        })
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Section>
        </div>

        <div className="space-y-4">
          <Section title="Links & artifacts" description="Relevant repos, previews, docs, and launch assets in one place.">
            <div className="space-y-4">
              <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <div className="text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-400">GitHub repo provenance</div>
                    <div className="mt-1 text-sm font-medium text-zinc-900">{project.github_repo_provenance?.label || "no repo yet"}</div>
                    <p className="mt-1 text-sm leading-6 text-zinc-600">{project.github_repo_provenance?.description || "No GitHub repo provenance is available yet."}</p>
                  </div>
                  {project.github_repo_binding?.fullName ? (
                    <span className="rounded-full border border-zinc-200 bg-white px-2.5 py-1 text-[11px] font-medium text-zinc-700">{project.github_repo_binding.fullName}</span>
                  ) : null}
                </div>
                {project.github_repo_provenance?.mismatch ? (
                  <div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
                    <div className="font-medium">Repo provenance mismatch</div>
                    <div className="mt-1 leading-6">{project.github_repo_provenance.mismatchReason}</div>
                  </div>
                ) : null}
              </div>
              {projectLinks.length === 0 ? (
                <EmptySectionState
                  icon={<ArrowUpRight className="h-7 w-7" />}
                  title="No links or artifacts yet"
                  description={artifactEmptyState(project.type, intake)}
                />
              ) : (
                <div className="space-y-2">
                  {projectLinks.map((link) => (
                    <a
                      key={link.key}
                      href={link.url}
                      target="_blank"
                      rel="noreferrer"
                      className="flex min-w-0 items-start justify-between gap-3 rounded-2xl border border-zinc-200 bg-white px-4 py-3 transition hover:border-red-200"
                    >
                      <div className="min-w-0">
                        <div className="text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-400">{link.label}</div>
                        <div className="mt-1 break-all text-sm font-medium text-zinc-900">{link.url}</div>
                      </div>
                      <div className="flex shrink-0 items-center gap-1 text-xs font-medium text-red-600">
                        Open
                        <ArrowUpRight className="h-3.5 w-3.5" />
                      </div>
                    </a>
                  ))}
                </div>
              )}

              <LinkEditor
                projectId={projectId}
                projectType={project.type}
                intake={intake}
                links={project.links}
                githubBinding={project.github_repo_binding}
                onSaved={({ links, githubBinding }) => setData((prev) => (prev ? { ...prev, project: { ...prev.project, links, github_repo_binding: githubBinding } } : prev))}
              />
            </div>
          </Section>

          <Section title="Recent updates" description="Important recent project activity and decisions.">
            {displayedRecentUpdates.length === 0 ? (
              <EmptySectionState
                icon={<Activity className="h-7 w-7" />}
                title="No recent updates yet"
                description="Once work starts moving, key approvals, delivery signals, and activity will appear here instead of leaving the section blank."
              />
            ) : (
              <div className="space-y-2">
                {displayedRecentUpdates.map((signal) => (
                  <div key={signal.id} className="rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm">
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <SignalBadge kind={signal.kind} />
                          <p className="text-sm font-medium text-zinc-900">{signal.title}</p>
                        </div>
                        <p className="mt-1 text-xs leading-5 text-zinc-500">{signal.detail}</p>
                        <div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-zinc-400">
                          {signal.actorName ? <p>Updated by {signal.actorName}</p> : null}
                          <p>{signal.sourceLabel}</p>
                        </div>
                        {signal.sourceDetail ? <p className="mt-1 text-[11px] leading-5 text-zinc-400">{signal.sourceDetail}</p> : null}
                      </div>
                      <span className="whitespace-nowrap text-[11px] text-zinc-400">{new Date(signal.timestamp).toLocaleString()}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Section>

          {documents.length > 0 ? (
            <Section title="Supporting docs & uploads" description="Uploaded references, files, and source material tied to this project.">
              <div className="space-y-2">
                {documents.map((doc) => (
                  <div key={doc.id} className="rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm">
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="rounded-full border border-zinc-200 bg-zinc-100 px-2 py-0.5 text-[10px] font-medium uppercase text-zinc-700">{doc.type.replace(/_/g, " ")}</span>
                          <p className="truncate text-sm font-medium text-zinc-900">{doc.title}</p>
                        </div>
                        <p className="mt-1 text-xs text-zinc-500">
                          {formatBytes(doc.size_bytes)}
                          {doc.mime_type ? ` • ${doc.mime_type}` : ""}
                          {` • Added ${new Date(doc.created_at).toLocaleDateString()}`}
                        </p>
                        {doc.storage_path ? <p className="mt-1 break-all text-[11px] text-zinc-400">{doc.storage_path}</p> : null}
                        {doc.url ? <a href={doc.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-red-600 hover:underline">Open link <ArrowUpRight className="h-3.5 w-3.5" /></a> : null}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Section>
          ) : null}

          {teams.length > 0 ? (
            <Section title="Teams" description="Who is attached to the work and how the load is shaping up.">
              <div className="space-y-2">
                {teams.map((team: any) => (
                  <div key={team.id} className="rounded-2xl border border-zinc-200 bg-white px-4 py-3 shadow-sm">
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-sm font-medium text-zinc-900">{team.name}</p>
                      <span className="rounded-full border border-zinc-200 bg-zinc-50 px-2.5 py-1 text-[11px] font-medium uppercase tracking-[0.14em] text-zinc-700">
                        {team.status === "on_track" ? "On track" : team.status === "waiting" ? "Waiting" : formatIntakeValue(team.status)}
                      </span>
                    </div>
                    <div className="mt-3 grid grid-cols-2 gap-2 text-xs text-zinc-500">
                      <span>{team.memberCount} members</span>
                      <span>{team.activeAgents} active now</span>
                      <span>{team.taskCount} owned tasks</span>
                      <span>{team.completedTasks || 0} completed</span>
                    </div>
                    {team.blockedTasks > 0 ? <p className="mt-2 inline-flex items-center gap-1 text-xs text-red-600"><ShieldCheck className="h-3.5 w-3.5" />{team.blockedTasks} blocked task{team.blockedTasks === 1 ? "" : "s"}</p> : null}
                  </div>
                ))}
              </div>
            </Section>
          ) : null}
        </div>
      </div>

      {showTaskModal && selectedTask && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={() => setShowTaskModal(false)}>
          <div className="w-full max-w-md rounded-[24px] bg-white p-6 shadow-xl" onClick={(e) => e.stopPropagation()}>
            <h3 className="text-lg font-semibold text-zinc-900">Task Details</h3>
            <div className="mt-4 space-y-4">
              <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4">
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <label className="block text-sm font-medium text-zinc-700">Task</label>
                    <p className="text-sm font-medium text-zinc-900">{selectedTask.title}</p>
                    <p className="mt-1 text-xs text-zinc-500">Status: {selectedTask.status?.replace("_", " ")} • Assigned to: {selectedTask.assignee_agent_id ? agentsById.get(selectedTask.assignee_agent_id)?.name : "Unassigned"}</p>
                    <div className="mt-2 flex flex-wrap gap-2">
                      <span className={cn("rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em]", getExecutionTone({ status: selectedTask.status, reviewRequired: selectedTask.review_required, reviewStatus: selectedTask.review_status }).badgeClassName)}>
                        {getExecutionTone({ status: selectedTask.status, reviewRequired: selectedTask.review_required, reviewStatus: selectedTask.review_status }).label}
                      </span>
                      {isBootstrapTask(selectedTask, bootstrapSprintIds) ? <span className="rounded-full border border-sky-200 bg-sky-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-sky-700">Kickoff</span> : <span className="rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-red-700">Active work</span>}
                      {selectedTask.review_required ? <span className="rounded-full border border-purple-100 bg-purple-50 px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-purple-700">{formatReviewStatus(selectedTask.review_status)}</span> : null}
                      {selectedTask.updated_at ? <span className="rounded-full border border-zinc-200 bg-white px-2.5 py-1 text-[10px] font-medium uppercase tracking-[0.14em] text-zinc-600">{formatRelativeTimestamp(selectedTask.updated_at)}</span> : null}
                    </div>
                    {selectedTask.task_type && TASK_TYPE_CONFIG[selectedTask.task_type as keyof typeof TASK_TYPE_CONFIG] ? (
                      <p className="mt-2 text-xs text-red-600">Structured type: {TASK_TYPE_CONFIG[selectedTask.task_type as keyof typeof TASK_TYPE_CONFIG].label}</p>
                    ) : null}
                  </div>
                  <ProgressRing value={taskProgressValue(selectedTask)} size={60} strokeWidth={5} />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-zinc-700">Status</label>
                <select
                  value={selectedTask.status}
                  onChange={(e) => setSelectedTask((prev: any) => (prev ? { ...prev, status: e.target.value } : prev))}
                  className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2 text-sm"
                >
                  <option value="todo">To do</option>
                  <option value="in_progress">In progress</option>
                  <option value="done">Done</option>
                  <option value="blocked">Blocked</option>
                  <option value="cancelled">Cancelled</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-zinc-700">Description / directions</label>
                <textarea value={taskDesc} onChange={(e) => setTaskDesc(e.target.value)} placeholder="Add notes or directions for the assigned agent..." rows={5} className="mt-1 w-full rounded-xl border border-zinc-300 px-3 py-2 text-sm" />
              </div>
            </div>
            <div className="mt-4 flex gap-2">
              <Button onClick={() => setShowTaskModal(false)} variant="outline" className="flex-1 rounded-xl">Cancel</Button>
              <Button onClick={handleDeleteTask} variant="outline" className="rounded-xl border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800">Delete</Button>
              <Button onClick={handleUpdateTask} variant="warm" className="flex-1 rounded-xl">Save</Button>
            </div>
          </div>
        </div>
      )}

      <StructuredTaskModal open={showTaskModal && !selectedTask} onClose={() => setShowTaskModal(false)} onCreate={handleCreateTask} creating={creatingTask} />
    </div>
  );
}
